### ISSUE TITLE
[Video Disruptors Grant]: Leveraging Live Video Spaces with Lens Creators

### ISSUE THREAD

**Issue by imthatcarlos** [livepeer/grants#151]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

The MadFi platform is for agencies and brands that want exposure to a crypto-native audience, through an efficient platform with on-chain payments + agreements, verifiable attribution, and AI-generated creative.

Our Bounties product connects agencies/brands with creators for sponsored social media posts.  

We’ve also built ClubSpace, a platform for creators to host live listening parties and promote their latest NFT drops - it’s essentially a Twitter Spaces experience, but with Lens profiles.

We want to integrate Livepeer video streaming for a “Twitter Spaces” / “Twitch” feature for Lens creators to broadcast live video / audio, promote their NFT drops, and host sponsored ad slots.

There are few live broadcasting apps in the Lens ecosystem, and in our opinion, none that have the potential to bring serious revenue to creators. We think that by combining our platforms - and integrating livepeer - creators can have a web3 alternative for monetization and engaging with their audiences. 

### Link to demo website (if applicable)

https://madfinance.xyz

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

This proposal is valuable to the Livepeer ecosystem for multiple reasons:
- ClubSpace's rebranded platform, along with the MadFi application, can serve as prominent showcases of Livepeer's capabilities, inspiring other platforms and developers to explore similar integrations
- This project opens up new avenues for creators to monetize their content through various strategies like token gating, sponsored ad slots, and tips. This can attract more creators to the Livepeer ecosystem, further expanding its user base and influence.

The primary risks that could make executing this project difficult include 
- technical challenges during the integration phase
- maintaining high-quality user experience after the integration
- ensure that the monetization strategies strike the right balance between incentivizing creators and retaining user engagement

### Please describe in details what your final deliverable for this project will be.

The primary objective of this project involves multiple layers of integration, intended to elevate the interactive experience offered by our platforms and bolster our value proposition for creators. Our main goals include:

- Rebranding ClubSpace's website to align seamlessly with MadFi's brand identity.
- Integrating Livepeer's innovative SDK to facilitate live video, audio, and chat. This will enable creators to host spaces that are either publicly accessible or restricted via token gating to a lens collect.
- Incorporating these updates into the ClubSpace SDK ([[ClubSpace SDK Documentation](https://docs.joinclubspace.xyz/)](https://docs.joinclubspace.xyz/))
- Embedding our enhanced SDK into MadFi's interface. This will empower creators with the ability to create a space directly from their dashboard.
- Introducing a “Live Spaces” feature on the MadFi dashboard, similar to Live Twitter Spaces. This will allow users to join a space, get redirected to the revamped ClubSpace page, engage with the video stream, see other attendees, and mint the drop.
- Implementing Bounties, providing creators with an opportunity to monetize their spaces through sponsored ad slots.
- Introducing additional monetization strategies as recommended by the Livepeer team. For instance:
    - A pinned lens post could become collectable during the live space, with real-time visibility of total revenue and the number of collectors (akin to Twitch tips).
    - Featured tips could act as money streams, with the profile picture of the user currently sending funds to the creator prominently displayed in the chat (integrated via Superfluid).

### Please break up your development work into a clear set of milestones

1. Integration of the new Livepeer SDK (demonstrated by Ericxtang) into ClubSpace to support live video and chat during spaces. Rebrand the site to mirror MadFi's aesthetic. The final product will be fully deployed to [joinclubspace.xyz](<http://joinclubspace.xyz>) or a suitable alternative domain. One person will lead the work here, our fullstack web3 engineer. For 2-3 weeks of work - $3,000
2. Update ClubSpace SDK to incorporate Livepeer's functionality. Two people will collaborate here as the sdk requires API + client-side work. For 2 weeks of work - $6,000. The SDK currently supports the ability to:
    - Create a new space, which includes the necessary infrastructure provisioning and configuration.
    - Fetch live data for a particular space.
    - Retrieve metadata on all ongoing spaces.
3. Embed the updated ClubSpace SDK into the MadFi application. This integration will enable users to view ongoing spaces, join them (redirecting to the ClubSpace app), and create a space from the MadFi app. Two people will collaborate here as the app requires SDK integration + client-side work. For 2-3 weeks of work - $5,000.

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Total: $14,000

Breakdown by milestone: 
1. Software development for 1 dev: $3,000
2. Software development for 2 devs: $6,000
3. Software development for 2 devs: $5,000

### Specify your team's long-term plans to maintain this software and upgrade it over time

We plan on supporting the MadFi app + this integration until we either
1) have a successful exit in the form of a sale
2) launch a token
3) raise money for an 18-month roadmap

We're currently applying for a few accelerators, which shows our commitment to seeing the project succeed

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

The cofounders of MadFi have been building on Lens since it was on testnet (April 2022) and have a combined 8 years of experience building in web3. The MadFi project was a hackathon finalist at the inaugural LFGrow hackathon hosted by Lens. Together with our friend (fullstack web3 engineer) who will be building this with us, we were a hackathon finalist at ethBogota with our ClubSpace project. Having only received hackathon prize money + grant money from Lens, we've pushed and maintained both apps in production. 

### How did you learn about the Livepeer Grants Program?

@ericxtang

### Was this project started at a hackathon or another web3 event? Which one?

LFGrow hosted by Lens, April 2022
ethBogota hosted by ethGlobal, October 2022

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

More info / screenshots / links: https://madfinance.notion.site/livepeer-grant-live-spaces-91cbd8e4a4ce4ed3ba20af2e68844e51

**Comment by hansy** [comment]
Thanks for applying @imthatcarlos! Our team will review your application and get back to you within 2-4 weeks with a decision!

**Comment by hansy** [comment]
Hi @imthatcarlos we'd love to fund this project! Let's hop on a quick call to iron out milestones and deliverables. Feel free to message me on Discord (hansy#9576).

**Comment by imthatcarlos** [comment]
happy to hear it @hansy ! will send you a friend request / DM

**Comment by imthatcarlos** [comment]
Hey Hans! Hope all is well. Just wanted to check in regarding these
milestones, we're a bit behind on schedule considering we needed some
updates on the livepeer studio api. I think we have one blocker right now
around the metadata for room users, but as soon as we're unblocked I think
we can finish off this first milestone.

Would it make sense to just bump things back one week? So delivering
Milestone 1 on July 13, etc

Cheers

**Comment by hansy** [comment]
Totally not a problem! I'm seeing some good discussions in the Discord about some of the changes we need to make on our end, so this make sense to me. Sorry about the blockers; we'll get them sorted as fast as we can.

But yeah we're flexible on the milestones, so whenever you're good, we'll be ready for you.

**Comment by imthatcarlos** [comment]
Great, all sounds good to me! I'll provide an update here on our progress
at the end of the week and the expected timeline

Cheers

**Comment by imthatcarlos** [comment]
Hey @hansy - sorry for the lack of activity here. Appreciate the team being able to make the changes required to the livepeer studio api. 

Happy to share that we completed the first milestone and deployed it to staging! 
https://staging.joinclubspace.xyz/

## What did we do
1. We integrated livekit components and used the livepeer studio to create two types of rooms during the create space flow, live video and live discussions
2. If space type is video or discussion, the host can share their url `/livepeer/{lensHandle}` so anyone can connect and join
3. We render lens profiles in the participants list, and in the chatbox 

## What's next
I want to share that the reason we were delayed with this grant is because of the build on base funding round. We were working on Creator Subscriptions in parallel and figured if we shipped that product, we would have the perfect integration of this live spaces feature. 

Read more here: https://twitter.com/madfiprotocol/status/1694337991899058558
And try it out: https://madfi.xyz/creators/madfinance

I'd like to propose a simplification of the next two milestones. Rather than build an sdk and then integrate into MadFi, we'd like to directly integrate live video and chat so that subscribers of a Lens creator have access to live spaces hosted by the creator. We think we can provide more value by focusing on this experience for creators and their top fans. 

Happy to share more info on a call!

**Comment by imthatcarlos** [comment]
hey sorry about that - the ux has gotten wonky since we've added and changed the options. it's likely that the only one you were missing is setting an nft drop or pinned lens post. you can try again and setting this as the pinned post: `https://lenster.xyz/posts/0x01a6-0x0139`

glad you think the ui/ux is good 🙏 we want to simplify it even further when integrating on madfi so it's just a click and go kind of thing.

so we're actually thinking of sunsetting clubspace as volume for music NFTs has really gone down. Instead, we'll merge this functionality into the madfi app for creators to make live broadcasts or discussion spaces right on the dashboard. So rather than us build an sdk for developers, we can focus on the experience for creators - skipping the second milestone altogether.

Sharing a screenshot here of the madfi dashboard for reference
![Screen Shot 2023-09-05 at 12 49 21 PM](https://github.com/livepeer/grants/assets/20136572/aadc35d7-2de0-40e2-a98c-d550572e0486)

**Comment by hansy** [comment]
Updating milestones here based on our conversation for pausing development on the SDK and integrating directly into the Madfi platform:

**Milestone 1:**
Integrate new Livepeer SDK functionality to ClubSpace to let creators go live with video
Update UI/UX on ClubSpace

**Milestone 2:**
Integrating ClubSpace into Madfi platform to allow creators to go live from there

**Milestone 3:**
Incorporate Livepeer SDK functionality into broader ClubSpace SDK

I'll mark `Milestone 3` as "tentative" given the new focus on building a tight experience for creators on Madfi.

**Comment by hansy** [comment]
Here's the tx hash for payment of Milestone 1: https://arbiscan.io/tx/0xc94cc6096cb9be4d00996915b5485513c3d8e7ce324ef7baafd2d62d89b70344. Let me know if you have any questions!

**Comment by imthatcarlos** [comment]
For visibility, here's our product on testnet! 

The creator can create the livestream from their dashboard on MadFi, and the live space itself has chat, screen sharing, and our Lens v2 Open actions are featured as well (the sponsored post). Coming to mainnet in a couple of weeks when we finish changes to our protocol 😎

 
![Screen Shot 2023-11-22 at 4 08 52 PM](https://github.com/livepeer/grants/assets/20136572/932cfec6-6171-4a44-946e-eaabaee17cea)

![Screen Shot 2023-11-22 at 4 09 00 PM](https://github.com/livepeer/grants/assets/20136572/18f484f5-4e25-4431-a46b-bbec6e9bf4b9)

![Screen Shot 2023-11-22 at 11 06 53 AM](https://github.com/livepeer/grants/assets/20136572/a5fcdcb9-2557-494c-89db-77f5e784b0be)

**Comment by hansy** [comment]
Awesome! Thank so much for posting the screenshots! Also, Milestone 2 tx has been confirmed. Here's the receipt: https://arbiscan.io/tx/0x4c4c8cc5d336edc6bf1a05a991739ce2139d6f36ed47029184032d9c6a36c131.
