### ISSUE TITLE
[Open LN Grant]:  QUIDLI

### ISSUE THREAD

**Issue by Lukerio** [livepeer/grants#155]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

Quidli is a micro on-ramp connecting Web 2.0 apps and web3 assets for you to embed crypto rewards and incentives into your collaboration workflows to boost participation and motivation. 
We want to enable you to recognize your top contributors natively in your Slack and or Discord, and is mainly used today by community managers who want to leverage community engagement on social media. Quidli users include the community teams at ConsenSys, the NEAR Foundation, ETHDenver, OrangeDAO, iExec, Flare Network, Tezos Foundation and CELO.
Quidli demo on discord: https://j.gifs.com/GRrk23.gif 

Here’s some key numbers we observed in 2022 on Quidli:
- nb of organizations: 1100+
- transaction volume: ~$2.4m
- nb of transactions: ~140k/month
- Types of orgs: Remote companies, online communities, web3 organizations, DAOs
- Use cases: Recognition, rewards, incentives, ambassador programs

### Link to public GitHub repo (if applicable)

https://github.com/quidli

### Link to demo website (if applicable)

https://quid.li/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Proposal for LivePeer:
We propose to you to build a light integration of Livepeer to Quidli by adding LPT to our API and hosted app environment. This will enable you to seamlessly distribute LPT tokens as rewards to the top active participants in your community directly in your Slack or Discord.
In addition to helping you internally share LPT tokens within your ecosystem, this integration lets us offer LPT to our user base of 1000+ organizations as an option via Quidli’s open token platform.

Through this initial partnership, we’d like to help Livepeer build an awesome community and ecosystem by enabling you to effectively boost community engagement using token incentives. Sharing more tokens with community members can help you to establish a positive alignment flywheel leading to more contributions and ultimately growth towards your main mission and objectives.

### Please describe in details what your final deliverable for this project will be.

Once the token integration is completed, $LPT token will be available as an option on:
1. Quidli web app
2. Quidli Slack app
3. Quidli Discord app
4. Any subsequent integrations built by Quidli

### Please break up your development work into a clear set of milestones

**Roadmap proposal:**
1st Milestone: Review of the token technical documentation (blockchain, smart contracts, tokens, etc.).
2nd Milestone: Testing to ensure $LPT is functional and usable within our environment.
3st Milestone: Review the integration with the Livepeer marketing team
Timeline: 3 weeks

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

We’re asking for $3,000 (in $LPT) to kick off the integration work.

### Specify your team's long-term plans to maintain this software and upgrade it over time

For non-crypto organizations (who don’t have tokens) we offer a SaaS model: Quidli is free up to 20 users, then Quidli costs $100 per month beyond that number of active users (i.e. $1,000 per year).
Our communities include remote and freelance (web2) organizations that use Quidli internally to incentize their freelancers or employees (mostly via Quidli for Slack).

For token orgs that want to use Quidli and integrate their own token, be aware that the integration cost (grant) also covers SaaS (so you won’t have to pay a SaaS fee once the LPT integration is successful).
There are no other fees for users (we don’t take fees on transactions), and you will have access to all Quidli features (weekly dashboard activity, emoji, unlimited group creation).

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Justin Ahn - CEO 
Previous experience: Helped launch high-growth e-commerce ventures in Southeast Asia, notably ZALORA & LAZADA Vietnam as EiR @ Rocket Internet 
LinkedIn profile link: https://www.linkedin.com/in/ahnjustin/ 
Role: Justin is the project coordinator 

Guillaume Figielski - CTO 
Previous experience: As blockchain engineer (incl. Solidity), launched ChainImpact, one of the first blockchain dev studios in France. Senior full-stack developer @ French multinationals including Airbus, Orange, and Peugeot.
LinkedIn profile link: https://www.linkedin.com/in/guillaume-figielski/ 
Role: Guillaume oversees token integration and product management 

Luke Vignal - Head of Business Dev 
Previous experience: Account Manager @Zendesk, Ex-Forrester 
LinkedIn profile link: https://www.linkedin.com/in/luke-vignal/ 
Role: Will be in charge of the partnership coordination and marketing efforts

Titus Decali - UX Designer
Role: Titus will be in charge of the front-end development 

Luis Marquez - Back End Dev 
Linkedin: https://www.linkedin.com/in/lmarqueze/ 
Role: Luis will be in charge of the Back-end development

### How did you learn about the Livepeer Grants Program?

Consensus 2023

### Was this project started at a hackathon or another web3 event? Which one?

No

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

You can find more info about our project, use cases and how it works in our gitbook section here:
https://docs.quid.li/gettingstarted/

**Comment by hansy** [comment]
Thanks for applying @Lukerio! We'll get back to you with a decision within 2-4 weeks!

**Comment by hansy** [comment]
Hey @Lukerio, apologies for the delay in response. Wanted to ask some quick clarifying questions if you don't mind:

1.) What sort of integration work needs to be done with Livepeer? Is it simply a matter of sending LPT to you for custody?
2.) Is the requested $3k amount inclusive of the LPT you'd like like us to share with you in your open token platform?
3.) Can you provide more details about the open token platform? Who's using it? What companies are participating? What sort of use cases exist for others outside of our community to share/receive LPT?

Thanks so much!

**Comment by Lukerio** [comment]
Hi @hansy,

No worries, thanks for the update! Here are some answers to your questions:
1) We integrate the LPT smart contract to our app's blockchain environment, as well as manage & mantain LPT in our app and across all current and future integrations
2) This $3k will cover the initial development work + our maintenance costs + give Quidli exposure to LPT + cover the first year's subscription for the Livepeer team
3) Today there are 500+ organizations using Quidli, with the majority not having/using their own token. LPT will be available as an option to these teams, as well as we can further arrange for open bounties from Quidli using LPT tokens (via an additional budget).

Let me know if everything is clearer or if you need more info, happy to help.

**Comment by Titan-Node** [comment]
I like the idea! 
@Lukerio As for the 20 free users, is this 20 community admins that have the ability to send tokens?
Or are tokens available to send by everyone?

**Comment by Lukerio** [comment]
Thanks for your feedback @Titan-Node !

A member will be consider as active as soon as they have a quidli account set up with tokens on their balance. 

As an example:
- If you tip a community member on discord => they received LPT token => they have a balance => Active member.

- If they created an account on Quidli and deposit some LPT on their account/balance => Active member

On the web app, you can add or remove members from your discord group if they are inactive and we will remove them from your active members group (they will not count as active anymore).
If you want to put a limit of 20 active users, we can send you a reminder once the limit is reach if its easier.

Regarding who has the right to send the token: as the discord admin, you can decide this rule. For example, you can define settings in the Quidli Discord bot saying that only Discord admin can use the Quidli app, or a specific roles, or everyone! It's up to you and your discord internal policy.

Let me know if my message help or need any further infos, always happy to help!

**Comment by Lukerio** [comment]
Hi @Titan-Node, @hansy,

Do you have any additionnal questions? What would be the next steps on your side?

**Comment by hansy** [comment]
I appreciate you answering our questions @Lukerio. 

From my side, while Quidli is certainly an interesting tool to better engage our community (especially in regards to giving them more options on what to do with their LPT), I think there needs to be a few more concerted steps we (the Livepeer community) need to take first before we can take advantage of a tool like Quidli. There are some compelling use cases with the app, but I think we first need to do a bit of homework on our end to hone in on what actions we want our members to take. Right now it's a little bit too wide open.

If possible, I'd like to revisit this in a month or two. I think we'll be better equipped then to give you a better answer. Would this be alright?

**Comment by Lukerio** [comment]
Hi @hansy ,

Thanks four your response! The most frequent use of quidli is to use our app on Discord to reward your ambassadors (to thank them for their efforts in content creation, for example). 

You'll find more documentation on use cases here: [](https://docs.quid.li/gettingstarted/).

Feel free to put some time if you'd like to deep dive into this topic : https://calendly.com/luke-436,

Best,

**Comment by Lukerio** [comment]
Hi,

Do you have any updates regarding our proposal?

Best,

**Comment by Lukerio** [comment]
Hi @hansy ,

Do you have any status update regarding your community initiatives? That would help me better manager the next steps.
If you have a community of devs, ambassadors or simply want to rewards your best community ambassadors, it should be interested to continue our discussion as we already worked with community teams on these use cases (iExec, Tezos, aleph Zero).

**Comment by hansy** [comment]
@Lukerio thanks for following up. Unfortunately at this time, we won't be able to fund this proposal. While we think your team has built a tool that would certainly benefit any crypto-native community (including ours), we simply haven't done the necessary prep work on our side to best utilize your offerings. Should that change and should we actively seek a tool to better engage and reward our members, we'll certainly reach back out.
