### ISSUE TITLE
[Microgrant]: everything

### ISSUE THREAD

**Issue by elliotBraem** [livepeer/grants#160]
### What is your project, and what problem does it solve?

Everything is a gateway for NEAR's [Blockchain Operating System](https://docs.near.org/bos) (BOS) which utilizes an on-chain Type system, enabling anyone to create anything. This type system not only allows data to be easily aggregated across the entire OS, but it also provides the building blocks for anyone to use the no-code tools for developing their own types and incorporating them in their widgets.

It is a hard project to describe -- it really is *everything*... and the problem it is trying to solve is the fight for the open web. BOS enables composable, decentralized front ends by storing React-esque code on chain and everything adds a Type system to make this front-end code structured and predictable. Introducing a "video" Type would empower developers to create innovative video applications while preserving user sovereignty and privacy.

### Link to public GitHub repo (if applicable)

https://github.com/near-everything/viewer

### Link to demo website (if applicable)

https://everything.dev

### How is Livepeer used for this project?

Livepeer will be used for the platform's video infrastructure. Everything currently has support for on-chain types such as markdown, images, tasks, and events. Through this grant, we will add a video Type and corresponding widgets for creating and viewing "Things" of this Type.

### How will you improve your project with this grant? What steps will you take to meet this objective?

The project will be improved by creating a video type that can be used across the entire operating system (and thus the open web), and some essential widgets so other developers can compose these features in their own projects/applications.

1. Create a video type (every.near/type/video) described with the necessary properties for rendering video
2. Create a create video widget (every.near/widget/every.video.create) which allows users to upload videos to Livepeer and saves the reference down to the SocialDB.
3. Create a view video widget (every.near/widget/every.video.view) which renders when a Livepeer reference is accessed from the SocialDB, and streams the video.
4. Necessary documentation for other developers to incorporate these widgets into their own applications.

### Was this project started at a hackathon or another web3 event? Which one?

The BOS was announced at EthDenver 2023 and the idea for [on-chain Types](https://social.near.page/p/efiz.near/87803726) was conceived shortly after, motivated by the mission of the everything project. I began working on the concept at EthDenver and have continued ever since.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Frankly, because of how easy BOS and the Type system makes it to develop anything, this implementation could be done by anyone willing to read the documentation. It's honestly beautiful. :')

But with extensive knowledge of NEAR Protocol, React, and Livepeer's infrastructure, our team is well-equipped to successfully execute this project. We have previously contributed to the NEAR community through various open-source projects and actively participated in hackathons and web3 events.

a. Elliot Braem
b. I built everything.dev and designed the Type system.
c. https://github.com/elliotBraem

a. Kiews development team
b. https://www.kiews.xyz/

### What is the project’s expected deliverable at the conclusion of the grant time period?

A working video feed where users can upload and watch video content.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

I want someone to be able to upload, scroll, and watch video content.
I want someone to be able to incorporate these Livepeer Widgets into their own applications built on BOS.

### How will this deliverable benefit the Livepeer ecosystem?

A video type on BOS would enable any BOS developer to utilize video in their own Widgets/Projects.

The everything project is also part of a broader initiative for the [BOS Builders Academy](https://academy.near.social/) and we can utilize this integration in the learning activities to illicit community feedback on the usability and effectiveness of the video type and widgets, and the growth of the Livepeer ecosystem through increased adoption of the platform for video use cases.

**Comment by hansy** [comment]
Thanks for applying @elliotBraem! We'll get back to you with a decision within 2-4 weeks!

**Comment by hansy** [comment]
Hey @elliotBraem! We'd love to fund this! I'm @hansy_ on Discord. Let's chat when you get a chance!

**Comment by elliotBraem** [comment]
@hansy That's great news! Of course, I've just sent a friend request from @efiz (494621039171731469)

**Comment by elliotBraem** [comment]
Hey @hansy and team! It's been really fun building with the Livepeer SDK.

You can view the components I've introduced to BOS in the library [here](https://everything.dev/efiz.near/widget/Library.index?widget=Library.Overview).
I haven't yet found the best way to show the Type, so you can see it [here](https://github.com/near-everything/bos-workspace/blob/main/apps/livepeer/type/video.jsonc) in the interim (I recently did an overhaul of how Types are described, so the old UI is broken).

These components can be composed together to build applications, such as this [one](https://everything.dev/efiz.near/widget/App.index) I built, where you can upload, view, and scroll videos. 

BOS is currently in the middle of a hackathon, and so I've made a [post](https://near.org/#/devgovgigs.near/widget/gigs-board.pages.Post?id=1153) with an open call for contribution for people to improve the app I built or use the components in their own application. My Telegram chats are excited right now :P

Tune in! And let's see what the community builds 😄

**Comment by hansy** [comment]
Yoooo this is awesome! Would you mind posting this in our [#developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) Discord channel? I think the community would love this! Also, if you have any socials, feel free to tag @livepeer in a tweet and we'll amplify as well!

**Comment by elliotBraem** [comment]
@hansy  Hahah I'm glad you like it!! I'll share in the discord rn. 

And I tweeted about it yesterday with tag if you wanna amplify that! https://x.com/elliot_braem/status/1697339243859681718?s=46

**Comment by elliotBraem** [comment]
Hey @hansy, so how does everything look? Are we good to close out this grant?

**Comment by hansy** [comment]
This looks great @elliotBraem! I'm happy to queue up the payment to close out the grant. Btw, how did the hackathon go?

**Comment by elliotBraem** [comment]
@hansy Awesome, thank you!

The hackathon went well! You can see the results [here](https://near.org/devgovgigs.near/widget/gigs-board.pages.Post?id=1377). I was a mentor during it and the Livepeer app I built wasn't a submission, but more of an idea I was hoping somebody to run with; unfortunately, nobody took the bait on the components...

But no worries! There is an [encode x near horizon](https://www.encode.club/encode-near-horizon-hackathon) hackathon that starts today and I would be happy to support a team that wants to pursue an app utilizing these components. I may have  a team that's interested, we'll see -- you know anyone? There should also be a BOS Hacks v2 at the end of October that we can prepare a more formal challenge for, if that is of interest. Then, there will be NEARCON in November, which can be another opportunity as well.

All in all, I'm pretty pumped about it all! It was a breeze utilizing the Livepeer SDK and I feel like these components are some sleepers just waiting to be used...

**Comment by hansy** [comment]
Hey @elliotBraem! Here's the tx receipt of the final milestone payment: https://arbiscan.io/tx/0x84928d7d0e97826cca71d0afd3c349b86c3adbf8f8d1448ae6218d9a6d166862. Great job on the grant! Let me see if we can find a team or two for some of the upcoming hackathons. Feel free to send over anyone our way in case they need help with anything. Other than that, we can officially close the grant. Let me know if you need anything else!
