### ISSUE TITLE
[Microgrant]: SafeUpload

### ISSUE THREAD

**Issue by AvinashNayak27** [livepeer/grants#164]
### What is your project, and what problem does it solve?

SafeUpload is a application that prioritizes user safety and content integrity. With advanced NSFW (Not Safe for Work) checks, it ensures that only safe and appropriate videos are allowed for upload

### Link to public GitHub repo (if applicable)

https://github.com/AvinashNayak27/SafeUpload

### How is Livepeer used for this project?

Once a video passes the NSFW checks, it is deemed safe for upload. The project then proceeds to upload the video to Livepeer.

### How will you improve your project with this grant? What steps will you take to meet this objective?

- Improve NSFW detection by considering different approaches like random snapshot selections
- Deploy the API
- Build a demo social media app with lens protocol

### Was this project started at a hackathon or another web3 event? Which one?

EthGlobal HackFS 2023

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

- Name:Avinash
- Github https://github.com/AvinashNayak27/

### What is the project’s expected deliverable at the conclusion of the grant time period?

- Improved and Deployed NSFW Alogorithm api
- Demo app with lens protocol

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Login to the app and upload a safe video and test algorithm with NSFW content video

### How will this deliverable benefit the Livepeer ecosystem?

By ensuring that only safe and appropriate videos are uploaded and streamed, SafeUpload can help improve the overall quality of content in the Livepeer ecosystem.

### How did you learn about the Livepeer Grants Program?

From [Shann](https://twitter.com/shanvasion)

### What's your wallet address?

0x2910135944f79d2B649209BC580fd9B6e73E82f1

**Comment by hansy** [comment]
Hey @AvinashNayak27! Thanks for applying! We'd love to fund this application! To kickoff the grant, we'll send you a 20% upfront payment. Is the wallet address in your application a good place (is it arbitrum-compatible?) to send LPT to?

**Comment by AvinashNayak27** [comment]
Thanks,I have updated the wallet address you can send the upfront payment to it

Wallet Address : 0x2910135944f79d2B649209BC580fd9B6e73E82f1

**Comment by hansy** [comment]
Hi @AvinashNayak27. You upfront payment (20%) has been confirmed: https://arbiscan.io/tx/0x928fea6b464f2924b75a63372e7ec509f9aaf805293157fc5df4c855077ffded.

With that, the grant is officially kicked off! You have a month to complete your deliverable, so September 1, 2023.

Let me know if you have any questions!

**Comment by AvinashNayak27** [comment]
Hi @hansy finished the milestones

1. Improved and Deployed API at https://safeupload.fly.dev
2. Demo with Lens protocol at https://lensdemo.vercel.app/ on mumbai testnet

You can find info on how to use the API at https://github.com/AvinashNayak27/SafeUploadDemo#readme
You can also go through the demo video https://www.youtube.com/watch?v=Y3aawqsjnl0

Let me know if any changes required

**Comment by hansy** [comment]
Wow that was quick! Will review and get back to you!

**Comment by AvinashNayak27** [comment]
Any update??

**Comment by hansy** [comment]
Hey! Here's the tx receipt for the completion of the grant: https://arbiscan.io/tx/0xd49d080aaaf657d759ccc2a2a1aa7f40d35d0b386a3cb97d6549e655c4ccf77c!

Great work! Let me know if you have any questions!

**Comment by AvinashNayak27** [comment]
Thanks had a great time building with you
