### ISSUE TITLE
[Open LN Grant]: DAOsign

### ISSUE THREAD

**Issue by TetianaRiabova** [livepeer/grants#165]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

**DAOsign** is a decentralized platform for agreements and automated workflows, with publicly verifiable, cryptographic proofs-of-signature, designed for DAOs and WEB3 companies.

Verifiable Signature is at the core of DAOsign and is based on 3 key proofs: **proof-of-identify, proof-of-authority, and proof-of-agreement**. Utilizing these proofs, DAOsign provides a platform to design and configure complex workflows that combine smart-contract-based automation with authorized approvals.

**Problem that we solve:**
Traditional methods of signing agreements, such as paper-based systems or legacy e-signatures, are prone to fraud and lack transparency, and offer no solution for verifying the signer's identity or authority to execute the agreement. Instead, these systems rely on costly legal proceedings to enforce agreements. 

**Our solution:**
DAOsign addresses the need for a secure and transparent way to sign, manage and automate agreements of all kinds with a configurable level of anonymity disclosure.

### Link to public GitHub repo (if applicable)

https://github.com/DAOsign

### Link to demo website (if applicable)

https://daosign.org/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

We believe that DAOsign holds significant value for the Livepeer ecosystem due to several reasons. Firstly, it aims to develop and integrate an agreement-signing tool, addressing a critical need within the Livepeer ecosystem. By streamlining and automating the agreement process, the tool enhances the efficiency of interactions between Livepeer participants, such as broadcasters, developers, and token holders.

Additionally, our tool brings transparency and trust to the ecosystem by ensuring that agreements are securely executed and recorded on the Livepeer blockchain.

Furthermore, DAOsign's integration with Livepeer introduces a standardized and user-friendly approach to agreement signing, making it more accessible for both existing participants and newcomers.

In short, our goal is to improve trust, accountability, and growth for Livepeer. This will help ensure long-term success in the decentralized video streaming world.

As for the risks, we have prepared a risk mitigation plan that includes technical, legal, and scalability risks but currently, there are no red flags that might stop us from delivering the grant scope in time.

![image](https://github.com/livepeer/Grant-Program/assets/122782612/08f8da11-9d86-4133-bac3-77d01837d33c)

### Please describe in details what your final deliverable for this project will be.

We consider our final deliverable as a **Mainnet version**. To deliver this milestone this work should be implemented: 

- Launching blockchain-stored and verified proofs version of DAOsign
- Production support 
- System resiliency 
- NFT-based Signer Authority Verification System

**Intended Outcome for Ecosystem/Users**: Publicly verifiable, flexible Signer Identity Verification System

**The expected time** for the delivery is Q3-Q4 2023

### Please break up your development work into a clear set of milestones

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-4ac261f4-7fff-4a21-4b59-553b297f1033"><div dir="ltr" style="margin-left:0pt;" align="left">

Grant Milestones | Milestone | Detail of work to be implemented to achieve milestone | Intended Outcome for Ecosystem/Users | Expected time required for delivery | Resource allocation
-- | -- | -- | -- | -- | --
Milestone 1 | Livepeer Testnet Version | The ability to store proofs on the Livepeer Testnet blockchain and verify them there.  The functionality includes: “Create an agreement” implementation; Assigning signers and observers; Implementation of Proof-of-Authority; Implementation of Proof-of-Signature; Implementation of Proof-of-Agreement; Early adopters program preparation | Ability to choose different user verifications for Agreement signers and verify user profiles. | Q3 2023 | 30 000
Milestone 2 | Incentivized Testnet version | Early Adopters Program launch; Online onboarding events; Feedback collecting; Roadmap adjustment | Adjusted roadmap based on Early Adopters' feedback | Q3 2023 |  
Milestone 3 | Mainnet version | Launching blockchain-stored and verified proofs version of DAOsign. Production support System resiliency; NFT-based Signer Authority Verification System | Publicly verifiable, flexible Signer Identity Verification System | Q3-Q4 2023 | 15 000
Milestone 4 | Mainnet version extended | Snapshot integration; GPT3 integration; Agreement legal templates | Extended DAOsign version launch | Q4 2024 | 5 000

</div></b>
</body>
</html>

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5cd14bdf-7fff-d5cd-4921-d670b4440fb4"><div dir="ltr" style="margin-left:0pt;" align="left">

Resource Description | hours per sp ($) | Cost per sp | total cost
-- | -- | -- | --
Blockchain developer: 200 hours | 8h | 120 | 24 000
Full stack developer: 75 hours | 3h | 100 | 7500
Tech lead: 50 hours | 2h | 120 | 6000
Project manager: 25 hours | 1h | 100 | 2500
QA/Business analyst: 25 hours | 1h | 80 | 2000
Community lead: 150 hours | 4h | 60 | 6000

</div><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Total SP: 25</span></p></b><br class="Apple-interchange-newline">
</body>
</html>

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Livepeer Testnet Version & Incentivized Testnet version - $30 000
Mainnet version - $15 000
Mainnet version extended - $5 000

### Specify your team's long-term plans to maintain this software and upgrade it over time

Our team is committed to the long-term maintenance and continuous improvement of DAOsign. And our plans include:

- Ongoing Support. We will provide regular updates and technical support to address any issues or bugs that may arise.
- Collaboration with the Community. As was mentioned above we're planning the launch Early Adopters Program, and gathering feedback, which will lead to the improvement of our tool and its functions. Also, we will actively engage with the community through social media, and community events to gather insights and incorporate valuable feedback into our development roadmap.
- Integration with Ecosystem Updates. Closely monitoring updates within the Livepeer ecosystem, we want to ensure seamless integration with any protocol upgrades or changes.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Eugene Fine (CEO & Founder) - Former CTO for ExplorerSurgical, VP of Engineering at
[GHX North America](https://www.ghx.com/digital-case-support/), tech advisor for [Polywrap.io](https://polywrap.io/#/). 
CEO for [DAOsign](https://daosign.org/), [CIDT](https://consideritdone.tech/).
LinkedIn link: https://www.linkedin.com/in/eugenefine/

Ramil Amerzynov (CTO) - 12+ years in building complex enterprise solutions, contributor to ETH and COSMOS ecosystems.
CTO for [DAOsign](https://daosign.org/), [CIDT](https://consideritdone.tech/).
LinkedIn link: https://www.linkedin.com/in/ramil-amerzyanov/

Misha Kushka (Technical Lead) - Blockchain expert with a solid tech background. Winner of Blockchain hackathons. Contributor to Tier1blockchains.
Linkedin link: https://www.linkedin.com/in/mkushka/

Oleksandra Burmenska (Business Development Director) - Blockchain advisor with a tech background. Contributed to NEAR, Polywrap, Axelar, GnosisSafe, and Avalanche ecosystems.
LinkedIn link: https://www.linkedin.com/in/oleksandra-burmenska/

Please, take a look at our portfolio with previous projects: https://docsend.com/view/fjrvjtyzgm7wgrkj

### How did you learn about the Livepeer Grants Program?

From the search engine.

### Was this project started at a hackathon or another web3 event? Which one?

N/A

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

Please, take a look at our pitch deck with more details: https://docsend.com/view/sbexkxn5su3ahdg8

**Comment by hansy** [comment]
Thanks for applying @TetianaRiabova! For Open Network grants, we typically ask grantees to post their project to the community and solicit feedback. Our decision to fund these type of projects is largely contingent on community interest and support. In the [Livepeer Discord server](https://discord.gg/livepeer), I recommend posting in either [#governance](https://discord.com/channels/423160867534929930/686685097935503397) or [#grants](https://discord.com/channels/423160867534929930/680142091174543362).

**Comment by TetianaRiabova** [comment]
Okay, I see. Thank you, @hansy! Will post it in Livepeer Discord then.
