### ISSUE TITLE
[Microgrant]: Turkish Translation of Livepeer

### ISSUE THREAD

**Issue by tolgayayci** [livepeer/grants#166]
### What is your project, and what problem does it solve?

This proposal aims to reach a large number of people whose native language is Turkish by aiming to translate the livepeer into Turkish. There is no Turkish option on the site and we can fix this problem with this grant.

### How is Livepeer used for this project?

In this project, livepeer docs and all requested pages will be taken as references and successfully translated into Turkish.

### How will you improve your project with this grant? What steps will you take to meet this objective?

This grant will be used to translate the desired parts of the livepeer into Turkish. After the scope and pages are determined, the translations will be completed and presented in the desired format.

### Was this project started at a hackathon or another web3 event? Which one?

No

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

**Tolga Yaycı (Translator)**

As a full-stack developer with 2 years of experience, I have honed my skills in software development, with a focus on dApp development in the past year. I have a deep interest in the Web3 and NFT space and have put my skills to the test by creating a number of relevant applications. In addition to my experience, I have developed detailed React and Next.js projects, further enhancing my ability to build robust and scalable web applications.

In addition to my technical skills, I have also been actively involved in the wider tech community. I have served as a Chainlink Community Advocate, Aave Turkey Community Manager, and Founding Chair of Gazi University ACM Student Chapter. My previous role as a Microsoft Learn Student Ambassador has also given me the opportunity to share my knowledge and experience with others. I have set of experiences and skills and particularly in the areas of full stack software development and community management.

I am a grantee of many protocols like Aave, Polkadot, Lens Protocol, Filecoin & Compound, by all of this technical and community experience I can easily handle with this task.

LinkedIn: https://www.linkedin.com/in/tolgayayci/

### What is the project’s expected deliverable at the conclusion of the grant time period?

- Translation of all pages which determined with Livepeer
- Publishing with the desired format on appropriate channels (github, other website workflow and so on)

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

-

### How will this deliverable benefit the Livepeer ecosystem?

When this deliverable is completed, it will be a livepeer that can be easily understood by native Turkish speakers.

### How did you learn about the Livepeer Grants Program?

On Website

**Comment by hansy** [comment]
Thank you for applying @tolgayayci! We'll get back to you with a decision with 2-4 weeks!

**Comment by tolgayayci** [comment]
Thanks for reply @hansy, 

Since there is a translation application, I could not give so detailed answers to the questions. If you have any questions, I am here and eagerly await your response.

**Comment by hansy** [comment]
Hey @tolgayayci! After talking with our docs team, we're currently not looking for translations just yet as the docs are still in a continual state of change. So at this time, we cannot find this application. However, should our needs change in the future, we'd love to reopen this application and reach out to you!
