### ISSUE TITLE
[Microgrant]: Demo.Vault

### ISSUE THREAD

**Issue by AdedamolaXL** [livepeer/grants#167]
### What is your project, and what problem does it solve?

Demo.Vault is a project focused on shining the light on two core values of the digital world, which is _iterative process_ and _buidling in public_ . While adjacently focused on developers, demo.vault can equally be useful to any creative who believes in iteration and building in public. Our modus operandi is to create conversations and value around products from prototype stage to product releases.

With Demo.Vault we will like to challenge the following problems: 

1. Lack of value around prototypes and demos: In the development process, prototypes and demos often serve as crucial steps towards the final product. However, they do not receive the attention or recognition they deserve and are often lost in the dumpsters and trashcans of the digital world. 
With the agency of decentralized file storage and communities, we believe we can push back against this flawed habit and regenerate new values that recognise and value the creative process involved in product development.
Demo.Vault will serve as a platform specifically designed to showcase and curate the process of early-stage creations up to their final forms.

2. Limited conversation and feedback: Building in isolation can make it difficult for developers and creatives to receive feedback and engage in meaningful conversations around their work. Demo.Vault aims to create a community where developers can interact, share ideas, and receive constructive feedback from peers and enthusiasts. It will encourage conversations that can lead to valuable insights and improvements.

Solving these two problems inherently also adds the following useful solutions, which are quite useful for early-stage products:

1. Visibility: Demo.Vault focus on shining the light on the creative process, by providing, a platform or prototypes, demos, and product releases to help increase visibility and create opportunities for recognition.
2. Community: Finding the right platform or community to share progress and iterate on ideas can be challenging. Demo.Vault aims to create an environment where developers and creatives can openly share their iterative processes, engage with others, and benefit from the advantages of building in public.

### Link to public GitHub repo (if applicable)

https://github.com/Digital-Artifacts/demo.vault

### Link to demo website (if applicable)

https://ethglobal.com/showcase/demo-vault-xkx6d

### How is Livepeer used for this project?

Demo.Vault started as an Hackathon project for HackFS with the focus of providing minting function that allows users to mint a demo uploaded to the gallery as NFTs. We have basically bootstrapped our ideas so far by leveraging Livepeer core sdk and API  functions like:

1. Upload a video asset: which allowed us to be able to upload demo videos to IPFS
2. Retrieve assets : which we used to retrieve the video assets and loop automatically generated demo video NFTs as shown in the gallery.
3. Mint a Video NFT: which added the minting functionality to the demo videos within the gallery

### How will you improve your project with this grant? What steps will you take to meet this objective?

To scale our product further, we will be building out a new feature centered around **Live Streaming**. For this purpose we will actively experimenting with Livepeer's:

1. Create a livestream
2. Stream OBS
3. Stream with Access Control
4. Multistreaming

At the end of one month of experimenting, we believe we will have built out a new cool feature that offers live streaming for live demos and interviews that everyone can view and participate in with the multistreaming on other platforms like youtube, twitch.

### Was this project started at a hackathon or another web3 event? Which one?

Yes. HackFS 2023 (ETHGlobal). Best Use Prize. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

We are a motivated team of two, who will like to continue building on our progress so far, and pushing our own technical abilities while building out a new cool product that people can actually use. 

Name - AdedamolaXL 
Github - [https://github.com/AdedamolaXL](https://github.com/AdedamolaXL)
email - [adedamolaxl@outlook.com](adedamolaxl@outlook.com)
LinkedIn - [https://www.linkedin.com/in/alexander-oyeniyi/](ur)

Name - Rodrigo Iglesias
email - rodri.iglesiasg@gmail.com
Github - https://github.com/raig1988/
portfolio - https://raig1988.github.io/portfolio/projects

### What is the project’s expected deliverable at the conclusion of the grant time period?

At the end of the grant time period, our application core feature will be a live-streaming app with video minting features.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Currently, the core mechanic of our project is minting demos as NFTs. We want to shift the core mechanic to focus on live streaming of demos, and interviews with the NFT minting becoming an important add-on that users take with them when leaving.

### How will this deliverable benefit the Livepeer ecosystem?

The two added solutions mentioned earlier, **visibility and community** that our product offers to early-stage products will also invariably apply to Livepeer by default since we are basically building on it.

It will be a bit like our Youtube got more popular because people started building and using it. With our focus on bringing creatives and developers to buidl in public and interact on the Livepeer platform, we are invariably adding to the Livepeer community and our product can even lead to inspiring the people using our product to buidl out some of their own on Livepeer via inspiration.

### How did you learn about the Livepeer Grants Program?

I found it by researching Livepeer after the hackathon.

### What's your wallet address?

0x30ba148609c6808f570571140C5D4b7Bf2CBcC12

**Comment by hansy** [comment]
Hey @AdedamolaXL! Thanks for applying! We'll get back to you with a decision within 2-4 weeks!

**Comment by hansy** [comment]
Quick question @AdedamolaXL: how do you plan on getting users for the platform? Is the community itself builders, or are non-builders also planned to be included (for feedback, suggestions, etc)?

**Comment by AdedamolaXL** [comment]
Good question! Right now our focus is building around developers especially the ones in the hackathon/accelarator phases of their projects.

Getting users for Demo.Vault will be a function of building a community around it and collaborating with our co-builders in the space. The target audience especially in the beginning will be fellow developers, creatives, product enthusiasts; people who like to tap into new products & invention early, NFT collectors. All of this people and the existing frens and community around them will be our target audience.

**To reach them:**

We will be doing alot of social media marketing on platforms like Twitter and LinkedIn where we will be highlighting this projects and creating conversations around of them with the added incentive of NFT minting for being a part of the live session for instance (more on this further down)

We especially will look to leverage other social media platforms like Youtube, Twitch using **Livepeer's Multistream** feature to extend our reach to our potential userbase and make the content even more accessible and easy to find!

Which leads to our content strategy! I have talked a bit about how demos can be valuable 'products' in their own right and this is what our hackathon project was about, now I will like to talk on how each content we create can be valuable for our users; both the devs, projects and viewers. 

Our value proposition is: how you can benefit and contribute from being a part of a project early. Every one of our video content which will be created on Livepeer will come with in-brand NFTs.

These NFTs will serve two purposes:

1. They will be collector items  which will appreciate in value as the project under spotlight grows, f.e: we intend to collaborate with the projects we will be highlighting on how this NFTs can be burnt in exchange for the project's token when they go public e.g having one NFT from a project ALPHA can be worth 20ALP when it reaches valuation. 

2. They will be a fundraising tool, while some of the collector items will be collected for free by virtue of participating in the live for instance. NFTs as a fundraising tool boills back to our initial product offering of 'demo videos as NFTs'. In this scenario, a demo video can be purchased as NFT as a way of contributing to a project and ensuring it continues going strong by the lovers of the project.

These two core content incentivization strategy will ensure:

- Added Value for NFT Holders who will see who see the potential of getting project tokens in the future.
- Increased Engagement: This will lead to increased engagement with the platform and the projects featured to see it succeed.
- Aligned Interests:  This alignment of interests will stimulate long-term as well as early community support for these projects while providing early access and benefits to its lovers.
- Promotional Tool - This direct support from the community we will help create around this project is the promotional tool that they need and everyone involved will be able to benefit from!

_one last one_
- Project Historification: The core driver of this project is how we can keep our digital history alive, and with blockchain we can make this very possible, by having demos, product releases videos minted as NFTs, we are creating a different kind of value system that might be worth more than what it is now (in a timeline of 1 - 100yrs). In the future, digital artifacts will be prized the same way Mona Lisa, Van Gogh is collected. The technology we are creating now will be worth collecting then because they will tell a story of how we got there. This demos andd product release videos minted as NFTs will be part of that story.
(sorry, this last one is more philosophy than user incentivization strategy, but i can't help it)

**Comment by hansy** [comment]
@AdedamolaXL As an update to the application status; we should have a decision for you and your team by the end of next week! Thank you so much for your patience and responding to our questions!

**Comment by hansy** [comment]
Hey @AdedamolaXL, after conferring with the committee, we'd love to fund this! Can you message me on Discord (@hansy_) and we can fine tune milestones together?

**Comment by AdedamolaXL** [comment]
sure! i sent you a friend request too!

**Comment by hansy** [comment]
Hey @AdedamolaXL, here's the tx receipt for the upfront payment: https://arbiscan.io/tx/0xbe2d6ed6d25ce79c5ade4571c63e4469ee349f9150af508e8d71b689bd7721fb.

With that, the grant is officially kicked off! The due date for completion of the grant is Oct. 27, 2023. Let me know if you have any questions!

**Comment by AdedamolaXL** [comment]
Pleased to deliver the project. We really enjoyed our time and frustrations :D
Github Link: https://github.com/Digital-Artifacts/MULTI
Demo Link: https://www.loom.com/share/16b27e9935b64f40b8bfb58ce09b21d0

**Comment by AdedamolaXL** [comment]
Excerpts from our user-testing report for MULTI:

### Summary
The user testing was fruitful and helped us identify core usability issues and insights crucial for refining the overall user experience. Top on the list is the unanimous demand that MULTI needs an ‘upload video’ feature that targets multiple platforms at the same time. Other features demanded: a ‘text overlay’ option that enhances their ability to communicate with viewers and a ‘schedule video’ option that gives them greater control over timing and planning their content releases. We also got an adjacent demand for ‘limited releases’ that can only be accessed through a paywall, creating a suitable revenue and distribution model for content creators.

Insights from testers revealed that 50% of their traction occurred on YouTube, while Twitch and Instagram each garnered 25%. Content creators especially expressed a keen interest in streaming to YouTube and Instagram simultaneously, with additional platforms like Facebook, Discord, LinkedIn, and Twitch noted as desirable. 

Among the testers, four (4) engaged in live testing on Zoom, comprising three (3) content creators and one (1) developer. The collective consensus judged MULTI as suitable, with content creators exhibiting significant enthusiasm for the app, valuing its potential for simultaneous streaming on multiple platforms. However, they also unanimously expressed a desire for a feature that enables them to upload pre-recorded content to various platforms simultaneously, given the nature of their work involving editing before publication.


### WHAT’S OUR NEXT STEP?

#### Short Term (January - February)
1. Refine MULTI's overall user experience and improve the user interface based on the users’ insights gathered. 
2. Add seamless recording and downloading while using MULTI to stream.
3. Market MULTI as a suitable alternative to Loom within hackathon communities.
   - Hypothesis - Hackers record demos and want a lot of people to see them.
   - Strategy - Promote MULTI as a tool for recording demos while also streaming to multiple platforms.
   - Expected Outcome - Hackers prefer to use MULTI because of its immediate advantages for marketing apps they have built.
4. Start the development of a new project with the specific purpose of helping content creators upload videos to multiple platforms at the same time.
   - Why? We recognize that creators may be tepid to use our app as it is now, but if we can solve the problem of uploading pre-recorded videos to multiple platforms at the same time: we invariably solve an important problem that was consistently brought up during testing and make our app more useful for them.
