### ISSUE TITLE
[Open LN Grant]: Integration Livepeer LPT x Charity Impact

### ISSUE THREAD

**Issue by vetkoek-en-fietse** [livepeer/grants#168]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

Currently, there are numerous crowdfunding platforms available for fiat currencies or single cryptocurrencies, and very few multichain solutions. This fragmentation forces charities and nonprofit organizations to create campaigns on multiple platforms, leading to inefficiency and impracticality, and hampers investors’ abilities to source charitable projects to which they wish to contribute. Our platform aims to empower the worldwide charity network through DeFi. By enabling charities to receive contributions in different currencies, we expand their opportunities for financial support. In order to enhance our multichain site, we have identified Livepeer as a vital roleplayer in the DeFi space. This project seeks to integrate LPT into our multichain platform, empowering the charity network within the Livepeer ecosystem. Once integrated, every NPO we onboard onto our platform will have a Livepleer wallet automatically generated and managed by our back-end system. This allows investors to donate directly to the NPOs in LPT.

### Link to public GitHub repo (if applicable)

https://github.com/malcacorp/Charityimpact-Open-source

### Link to demo website (if applicable)

https://charityimpact.io/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

This project will benefit the Livepeer community because:
1. Our integration code will be open sourced, to be freely used by other developers building on Livepeer.
2. Once we launch the platform with multiple blockchains integrated, we will migrate our existing charity network from SAI (https://www.sai.ngo/) and BeeTogether (https://bee-together.org/) to the new platform. With each wallet and transaction generated through our site, we empower the ecosystem of each integrated crypto-currency and add to the value of the coin itself. By running ads we aim to boost the platform and increase its reach, bringing more people into its ecosystem. 
3. An integration with our platform provides Livepeer with exposure to our social media audience, amplifying visibility and increasing brand recognition.
4. Cross-linking with Charity Impact enhances credibility and trust, attracting potential investors and users.
5. A blockchain's involvement in social good is beneficial on multiple fronts. Firstly, it enhances their reputation as responsible actors in the digital landscape. By actively contributing to social causes, blockchains demonstrate their commitment to making a positive impact. Secondly, aligning with social good meets the expectations of an increasingly conscious public. People appreciate and support entities that prioritize social welfare. Finally, the collaboration between corporates and blockchains amplifies their collective ability to drive meaningful change in the world. Together, they possess the potential to tackle global challenges and foster a better future for all.

### Please describe in details what your final deliverable for this project will be.

Once this project is complete, donors will be able to donate to nonprofit organizations in LPT through our website https://charityimpact.io/

Back-end architecture: a Livepeer wallet and an automatic generation of the wallet for each NPO will be integrated within the site.
Front-end architecture: payment forms, a donation tracking system, and a real-time currency evaluation system will be integrated with LPT.

### Please break up your development work into a clear set of milestones

The integration of the Livepeer currency onto the platform will take a maximum of three months. The project will be developed using PHP integrated with Python. We have already tested our concept through the successful integration of NEAR Protocol on our live site. Our team will now use our existing architecture that is currently running our platform to integrate with Livepeer. This project is broken up into three milestones:

Milestone 1: back end
Duration: 4 weeks
Deliverables: 
1. Integrating the Livepeer wallet.
- Functionality: once complete, charities who already have a Livepeer wallet can create a profile
- Measurement: once complete, we will provide you with a code and demonstration
2. Integrating the automatic generation of the wallet for each organization. 
- Functionality: once complete, charities who do not own a Livepeer wallet will receive an automated wallet
- Measurement: once complete, we will provide you with a demonstration

Milestone 2: front end
Duration: 6 weeks
Deliverables:
1. Integrating LPT into the payment form; 
- Functionality: once complete, the payment form will give LPT as a donation option
- Measurement: once complete, we will provide you with a code and demonstration
2. Integrating LPT into the existing donation tracking system and the CRM
- Functionality: once complete, the LPT numbers and the system are updated automatically
- Measurement: once complete, we will provide you with a code and demonstration
3. Integrating LPT into the email system; 
- Functionality: once complete, tax documents will be automatically emailed to donors upon completed LPT transactions
- Measurement: once complete, we will provide you with a code and demonstration
4. Integrating LPT into the real-time currency evaluation function.
- Functionality: once complete, LPT will be added to the real-time currency evaluation which will be automatically updated
- Measurement: once complete, we will provide you with a code and demonstration

Milestone 3
Duration: 2 weeks
Deliverables: 
1. Final testing and changes.
- Functionality: once complete, donors can donate to NPOs in LPT with total and seamless integration into the site’s back end and front end architecture.
- Measurement: successful transactions to NPOs in LPT.

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

The amount of $ 17 000 USD is being used to cover the costs of our two developers through the integration process. We have contracted Malca Corporation to build the software, who are charging a set price for the integration, based on the country’s standard salary rates for developers. The two developers have a combined experience of 12 years developing on the blockchain. 

The budget is divided across the three milestones accordingly: 

Milestone 1
Duration: 4 weeks
Budget: $5 000 USD
Full-time employees: two developers

Milestone 2
Duration: 6 weeks
Budget: $10 000 USD
Full-time employees: two developers

Milestone 3
Duration: 2 weeks
Budget: $2 000 USD
Full-time employees: two developers

### Specify your team's long-term plans to maintain this software and upgrade it over time

All transactions generated through our platform are subject to a 3.8% transaction fee which will be used to manage, maintain and improve the platform.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Steven Malca (founder, CEO and chief software engineer) is a software developer with a decade of experience in the field. He specializes in the development of world-class CRM and ERP systems for businesses of all sizes (https://malcacorp.com/). In 2016 Steven entered the charity sector, establishing the South American Initiative (SAI) (https://www.sai.ngo/).
Location: USA
LinkedIn: https://www.linkedin.com/in/steven-malca-66135099/
GitHub: https://github.com/malcacorp?tab=overview&from=2023-06-01&to=2023-06-30

Claudia Peter (co-CEO) has amassed 15 years of experience in marketing and communications over various sectors. In 2020, Claudia founded BeeTogether (https://bee-together.org/), an association that explores innovative fundraising methods, including the utilization of NFTs. 
Location: Switzerland
LinkedIn: https://www.linkedin.com/in/claudiapeter/

Joshua Hernandez (lead software engineer) is a skilled engineer with 7 years of experience in the field. Joshua is proficient in PHP, C++, and Python development. With expertise in blockchain technology, he has contributed to the creation of innovative cryptocurrency networks, showcasing his talent for cutting-edge software development.
Location: USA
GitHub: https://github.com/malcacomputerengineering

Yudith Serrano (software engineer) is a talented PHP engineer specializing in CRM and ERP development. With a strong expertise in designing and implementing efficient software solutions, Yudith excels in creating custom systems that streamline business processes and enhance productivity. Yudith has 5 years of experience in the field.
Location: USA
GitHub: https://github.com/ycsa91-malcacorp

With their extensive experience and connections in the charity sector, Steven and Claudia bring to the project a wealth of resources and relationships, providing Charity Impact with the means to tap into a wide range of expertise, support, and opportunities. By leveraging these unique resources and relationships, Charity Impact is poised to make a significant impact and achieve success in its charitable endeavors.

Our development team (https://malcacorp.com/), led by our founder and CEO Steven Malca, has extensive experience working on large-scale projects, including Instant Vital Records (https://instantvitalrecords.com/), Global Tal (https://globaltel.com/), and South American Initiative (https://sai.ngo/). These projects have required significant expertise in various domains, such as data management, security, and scalability. Leveraging their knowledge and skills, our team has delivered innovative solutions that have made a positive impact on people's lives.

### How did you learn about the Livepeer Grants Program?

We learnt about the program through research on the Livepeer website. 

### Was this project started at a hackathon or another web3 event? Which one?

No. 

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

Our competitor, The Giving Block, is a multichain donations platform through which nonprofit organizations can add donation forms to their websites. While Charity Impact does offer this service to our NPOs, we also allow NPOs to raise funds for specific projects, with custom landing pages and project tracking. The Giving Block has a registration fee of $2 000 USD, inhibiting smaller charities from accessing the platform and thus the DeFi system. Charity Impact allows any charity to join our platform if they are a legally registered entity in their country of origin and we do not have a registration fee. Management of our platform is funded by a 3.8% transaction fee on all donations. All charities will be vetted by our team to verify their legality before their approval is granted and their wallets generated.

[Livepeer Open Grants Program_Charity Impact.pdf](https://github.com/livepeer/Grant-Program/files/12093932/Livepeer.Open.Grants.Program_Charity.Impact.pdf)

[NEAR_Reference-Letter_Claudia-Steven.pdf](https://github.com/livepeer/Grant-Program/files/12093940/NEAR_Reference-Letter_Claudia-Steven.pdf)

**Comment by hansy** [comment]
Hey @vetkoek-en-fietse! Thanks for applying! We'll get back to you with a decision within 2-4 weeks!

**Comment by hansy** [comment]
Hi @vetkoek-en-fietse. Thank you again for applying; however at this time, we've decided not to fund this application. But please continue building, and feel free to apply again in the future. We'd love to stay updated on your progress!
