### ISSUE TITLE
[Video Disruptors Grant]: LivePeer support for Decentraland Ultra Low Latency Components.

### ISSUE THREAD

**Issue by carlton355** [livepeer/grants#171]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

I have developed components that support Ultra Low Latency for the Decentraland SDK. Details of the original grant proposal are here:

https://governance.decentraland.org/proposal/?id=858cd0a0-0c18-11ed-92a2-218eab5ea42b

The components hit an important milestone recently where the Decentraland testing community (Testing Tuesday) tested decentraland scenes and the results were good.

Following conversions with Eric Tang, this proposal aims to add support for LivePeer WebRTC.

The project includes development, testing phases, documentation writing, working with a scene developer for user acceptance testing and with the LivePeer community.

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

If this is done right it unlocks the use of LivePeer as a first class option for ultra low latency streaming into Decentraland. Many new Metaverse applications become possible with these components. The standard decentraland video components do not support low latency and that makes realtime video infeasible.

If LivePeer is not successfully integrated into the components then video users who require low latency in the Metaverse will need to switch to other servers. This grant ensures that a high level of attention and resources will be focused on making LivePeer a first class choice for realtime streaming within Decentraland.

Many of the risks associated with this project have already been mitigated during the Decentraland grant phase. The components work well and deliver ultra low latency video into decentraland.  This project largely involves reproducing something that already works with another server infrastructure.

Of course, there is much work to do. Code will need to be refactored as we move from supporting one provider to two providers and success requires support, testing, community involvement, working with LivePeer and Serraform and production of documentation.

### Please describe in details what your final deliverable for this project will be.

Delivery of LivePeer support for the decentraland VideoRealtimeComponents. 
Documentation and code examples. These may be able to be included in the Decentraland SDK documentation as well as on the LivePeer website.
Tested and working on Chrome and Safari. 
Work with at least one LivePeer user implementation in Decentraland that wishes to use the low latency components (if opportunity arises).

### Please break up your development work into a clear set of milestones

I am the architect and developer of the Low Latency Video Components and will carry out all the work on the milestones below.

**Milestone One - Core Development - Six weeks - $7500**

Deliver the core support for LivePeer within the Realtime Video Components. This involves:

- Research LivePeer system with a view to performing a component integration.
- Work with Serraform to understand their system and how it works.
- Build the LivePeer Driver component that handles all the connections through to the livepeer system and its webrtc signaling etc.
- Update any parts of the component that require changes to support LivePeer.
- Refactor the code to neatly support two drivers.
- Ensuring this runs smoothly on Chrome.

**Milestone Two - User Testing - Four weeks - $5000**

- Test across browsers Chrome, Safari and Edge and on Mac and WIndows.
- Perform user acceptance testing with community members from the LivePeer community.
- Collect feedback from team and feature requests or changes/bug fixes.
- Implement any changes.

**Milestone Three - Completion - Two weeks - $2500**

- Write documentation for the video component (for Decentraland, Serraform and LivePeer, if required)
- Work with a LivePeer Decentraland user to do an actual implementation into a scene.
- Be available to other community members for feedback, comments, support.

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Total budget $15,000

I am the architect and developer of the Low Latency Video Components and will carry out all the work on the milestones. Some costs will be associated with running cloud servers. 

### Specify your team's long-term plans to maintain this software and upgrade it over time

This is an ongoing project that will continue after this grant has run its course.

The components currently run with SDK 6 of the Decentraland SDK and we will be working more with Decentraland to support SDK7. After the SDK7 integration the code will likely be handed over to the Decentraland Foundation for future maintenance and updates or further funding sort from Decentraland.

This LivePeer project will move with the main decentraland low latency code.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

It makes sense that I do this work as I am the original architect and developer of the Low Latency Components.

I'm also a 5x CTO and have successfully led over 500 successful software projects. 

### Who is your target user group? How do you plan on getting your users to use this?

Anyone who wants to use Low Latency Video in Decentraland will need to user these components. They are integrating into the main decentraland codebase and documentation.

### How did you learn about the Livepeer Grants Program?

From Eric your CTO who contacted me after reading about my Decentraland work.

### Was this project started at a hackathon or another web3 event? Which one?

Decentraland grant proposal.

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

I'm super excited to be doing this work and working with the LivePeer community. Ultra Low Latency video will be a real game changer for application in the Metaverse. It's exciting to be working with a team that shares the vision.

**Comment by hansy** [comment]
Thanks for applying @carlton355! We'll get back to you with a funding decision with 2-4 weeks!

**Comment by hansy** [comment]
Hey @carlton355! After conferring with the committee, we'd love to fund this project! Would you mind DMing me on Discord (@hansy_) so we can fine tune milestones together?

**Comment by hansy** [comment]
Hey @carlton355! After conferring with the committee, we'd love to fund this project! Would you mind DMing me on Discord (@hansy_) so we can fine tune milestones together?

**Comment by carlton355** [comment]
Thank you for the good news. Will ping you this morning.

I’ll also need to get set up with LivePeer video. I’d need to be able to
set up a stream in the same way that an end user would do it for
Decentraland. And also be able to get the stream up and running on a web
page.

Both of these should be fairly straightforward.

**Comment by carlton355** [comment]
I’m carl (carl355) on discord. Sent you a friend request.

**Comment by carlton355** [comment]
**Deliverables update:** Following discussions with LivePeer today we will be working to target other Metaverses. To that end we have mutually decided to add these further deliverables to the grant:

(a) A short document describing a high level overview of what is involved to get low latency video working on other Metaverses (technical lift) 
(b) a proposed roadmap/gameplan for how this component and LivePeer can deliver on that requirement.

LivePeer to assist with a shortlist of Metaverses to target.

**Comment by hansy** [comment]
Awesome! We'll add the deliverable to your last milestone. I'll queue up the upfront payment (20%) and upon confirmation I'll post the tx receipt along with the updated timetable for the milestones!

**Comment by carlton355** [comment]
Milestone 2 will now also include a target of 20 testers to participate in the User Testing phase.

**Comment by carlton355** [comment]
Update to keep this thread alive: We are continuing to work on delivery for Milestone One.

**Comment by carlton355** [comment]
![image](https://github.com/livepeer/grants/assets/21988976/ea2a3e1b-b60c-4c57-888a-12e8fa201698)

We have completed Milestone One on schedule. LivePeer now has a working ultra low latency WebRTC video component. We will move forward today into the testing phase.

The image shows the working test in a decentraland scene.

**Comment by hansy** [comment]
Thanks @carlton355 for the update! Is there a way I can test this?

**Comment by hansy** [comment]
Thanks for the demo! Here's the tx receipt for Milestone 1: https://arbiscan.io/address/0xb7c0dc404C2ce1b2226c709eCa6d8479B1FB80dc.

**Comment by carlton355** [comment]
Milestone 2 was completed yesterday after a demo session at the LivePeer Watercooler.

Documentation available:

- Testing Document results from LivePeer community testing focused on browser testing and video latency. (15 results)
- Testing Documentation from Decentraland testing focused on video, resource management, performance (6 results).

Community Engagement

- Engagement from both the LivePeer and Decentraland side. (everyone who took the time to test was documented).
- Presented yesterday at the LivePeer watercooler with TitanNode and ~20 others. We ran a Decentraland scene together where many joined to watch video and test latency.
- One small pending issue with sound discovered yesterday. Investigating and likely on LivePeer WebRTC side. "Video audio track not audible upon video stop and restart." Investigating and can already reproduce in browser.
- One cool comment from yesterday "I'm envisioning a virtual music festival with multiple stages!"

**Comment by carlton355** [comment]
Documents for Milestone 2
[Live Peer Testing2.pdf](https://github.com/livepeer/grants/files/13284814/Live.Peer.Testing2.pdf)
[LivePeer Testing Results.pdf](https://github.com/livepeer/grants/files/13284815/LivePeer.Testing.Results.pdf)

**Comment by carlton355** [comment]
Milestone 3 was completed yesterday.

- Documentation. **Streaming with WebRTC.**  This is concise and written to be inserted into the Decentraland video [documentation](https://docs.decentraland.org/creator/development-guide/video-playing/). I have used LivePeer in the sample code to encourage use of LivePeer. Also included a link to LivePeer documentation.  The final decision on what will be included will be with Decentraland. 
- Sample Scene. Sample code. It is anticipated that this will be added to the Decentraland code samples page on github.

[Streaming with WebRTC.pdf](https://github.com/livepeer/grants/files/13432114/Streaming.with.WebRTC.pdf)
[sample_scene.ts.txt](https://github.com/livepeer/grants/files/13432117/sample_scene.ts.txt)
