### ISSUE TITLE
[Microgrant]: Decentraclasses

### ISSUE THREAD

**Issue by HiberNuts** [livepeer/grants#172]
### What is your project, and what problem does it solve?

Decentraclasses is a decentralised ed-tech platform in India that aims to decentralize education and empower learners to monetize their knowledge through staking in their own courses. By bridging the gap between web2 and web3 awareness, providing mentorships, and offering tradable courses with lifelong incentives, Decentraclasses enables individuals to leam, earn, and test their skills in a decentralized manner, fostering a more inclusive and rewarding learning experience.
Socials: https://bento.me/decentraclasses

### Link to public GitHub repo (if applicable)

https://github.com/DecentraSchool/decentraclasses

### Link to demo website (if applicable)

https://decentraclasses.vercel.app/

### How is Livepeer used for this project?

Decentraclasses is a decentralized ed-tech platform that primarily focuses on Video based engagement courses. Our whole model revolves around video streaming and on demand video courses. This Would require good video streaming and gateway architecture to make the process seamless to the user and enhance user experience. Livepeer being market leader in the video infrastructure we would benefit by using livepeer as our video storage provider on web3. We are also planning on using livepeer for real time video streaming courses for our cohorts so that instructors can take sessions live supported by livepeer.

### How will you improve your project with this grant? What steps will you take to meet this objective?

Our phase wise plans are as follow:
PHASE 1 IN PROGRESS TO BE COMPLETED BY August 2023)

- The alpha version of the Product is in progress with user authentication and buying of courses and Video-based Assessment and a Strict Assessment Policy
- PR and Community Building

PHASE 2 (IN PROGRESS TO BE COMPLETED BY NOV 2022)

- Course Selling feature with rewards based on performance.
- Marketing and Promotions
- EARN Features will be-
- Community Monetization - P2R ( Pay to reveal )
- Partner up with companies to list Bounties/Surveys and Micro Tasks
- Partner up with companies to list jobs/internships
- Early NFT Drop for the first 1000 members in exchange for an initial product review

Phase 3 (FUTURE: DEC 2023 )

- NFT-based Course Completion - Proof of Learning
- Mentorship and 1:1 session connect with Industry experts.
- Customized ROADMAP based on user behaviors.
- Coding Leagues and P2P multiplayer
- Cohorts and short content courses
- LNPL(Learn Now Pay Later )
- Project Based Learning (Practical Hands-on experience)

### Was this project started at a hackathon or another web3 event? Which one?

This project was started at Hack web3 conf hackathon
Relevant Link:
https://devfolio.co/projects/decentraclasses-9f51 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

- Aryan Ghosh, Founder (Decentraclasses)
Ex Co-founder of EVNTORG.COM
Expertise - Fintech, Ed-etch, e-commerce etc.
Manages Marketing and operations of the project.
Linkedin: https://www.linkedin.com/in/aryanghosh001/
Twitter: https://twitter.com/aryanghosh001

- Raghav Jindal CTO (Decentraclasses)
Intern at TNEA (Tamil Nadu engineering asscoiation - https://www.tneaonline.org/)
An experienced and refined developer with comprehensive proficiency in the field of Blockchain development from writing, testing and deploying smart contracts on various chain along with Full stack - Web and App development, using technologies like - Flutter, React Js , Node Js, Database, Ui libraries, API.
Github: https://github.com/HiberNuts
Linkedin: https://www.linkedin.com/in/raghav-jindal-a56538212/

- Anjesh Agrawal, Product & Business Development Manager
Linkedin: https://www.linkedin.com/in/anjeshagrawal/
As a Product and Marketing Manager at GlasierInc, I leverage my marketing and sales skills to build and grow a vibrant community of blockchain and crypto enthusiasts. I also manage events, partnerships, and campaigns to increase brand awareness and engagement.

### What is the project’s expected deliverable at the conclusion of the grant time period?

At the end of the grant time period, we are expecting to complete the First two phases mentioned above in the description. Users will be able to make use of our learn to earn models and dynamic NFT's will be granted for each step in the course completion.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

We want users/students to learn through our platform and make use of comprehensive video courses along with that they also have to answer quiz prompts for each video assessment in order to claim Dynamic NFT for course completion.

### How will this deliverable benefit the Livepeer ecosystem?

- Web3 is in highly need of a good ed-tech platforms, one reason being even that platforms that are teaching web3 content are on web2 based infrastructure. We want to break that stereotype and establish that possible application can be built on web3 ecosystem without depending on centralized infrastructure.
- Eg: AWS for data storage and video streaming.

- With more and more users onto platform will not only benefit the web3 ecosystem but also livepeer as it is your technology that made execution of this project possible.

- Additionally, we would love to add a course dedicated to livepeer that teaches students' about the livepeer ecosystem and how the real-time video streaming works. We would be contributing in the growth of livepeer, by promoting use of livepeer rather than any traditional costly centralized system.
- This would also help Livepeer to achieve its goal of democratizing access to video infrastructure and opening up new possibilities for creators and developers.

### Who is your target user group? How do you plan on obtaining them?

Our target group are the learners, regardless of age, experience, profession, sex. Anyone with aim to learn are our target audience.
We have also previously built a edtech platform that coordinates with many colleges all around India and built a community of students from all Tier 1,2,3 type colleges/Universities. We can make use of that community and bring them onboard to the platform.
Additionally, our marketing team is giving their all to promote this platform on social media and with constant social engagement we can attract many potential long-term users.

### How did you learn about the Livepeer Grants Program?

We have already connected with team at livepeer and had a detailed meet session with Alex Mexicotte and share a telegram group with Eric and Alex as well. It was Alex that guided us towards the process and also gave great inputs in order to improve the platform.

### What's your wallet address?

0x0a960Fa6158f4d7aDfA2A3dA5408aB6efd4A5C5A

**Comment by hansy** [comment]
Hey @HiberNuts. After conferring with the rest of the grants committee, we've decided not to fund your project at this time. I know this may not be the decision you were looking for, but we encourage you to continue working on your project and keep us updated on your progress! Please feel free to apply again in the future with additional updates and traction!
