### ISSUE TITLE
[Microgrant]: Web3Arabs

### ISSUE THREAD

**Issue by KhairallahA** [livepeer/grants#173]
### What is your project, and what problem does it solve?

Web3Arabs is an open-source platform to learn Web3 for free and help all Arabic speakers in Middle East and North Africa to learn Web3 easily.

### Link to public GitHub repo (if applicable)

https://github.com/Web3Arabs

### Link to demo website (if applicable)

https://web3arabs.com

### How is Livepeer used for this project?

Livepeer will be used in tutorials that help the community and developers create video applications, and use Livepeer features in their applications.

### How will you improve your project with this grant? What steps will you take to meet this objective?

- Giving students NFTs degree at the end of courses.
- Start a marketing plan to get hundreds and thousands of students to start learning Web3.
- Organize multiple spaces and lives to help students learn Web3 easier.

### Was this project started at a hackathon or another web3 event? Which one?

No. Web3Arabs becomes the first open source Arabic platform help devs to learn Web3 and get job.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Web3Arabs team works great efforts to provide the best educational resources through Web3 specialists.

Khairallah AL-Awady
https://github.com/KhairallahA
https://linkedin.com/in/khairallah-w3a
https://twitter.com/Eng_khairallah1

Ahmed Abdelmalek
https://github.com/0xPeterPan
https://linkedin.com/in/ahmedabdelmalek
https://twitter.com/PeterPanYes

### What is the project’s expected deliverable at the conclusion of the grant time period?

Community growth at a very large rate, supporting the community with resources and solving their problems, and granting NFTs degrees to students.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

I want everyone who joins Web3Arabs to get all the resources needed by Arabic-speaking developers or entrepreneurs in the Web3 space who have not been able to build value-added projects due to educational resource constraints, so that everyone can integrate Livepeer tools with different tools into their projects that make an impact in Web3 space.

### How will this deliverable benefit the Livepeer ecosystem?

By bringing in the many Arabic speaking developers and enthusiasts in the Middle East and North Africa to build unique applications and to be part of the growth of the web3 ecosystem in MENA that is growing exponentially.

### Who is your target user group? How do you plan on obtaining them?

Our mission is not an easy one, and this is what makes the educational resources in MENA very few because of the difficulty in providing basic educational resources to students and the lack of awareness about Web3, which many developers still do not know about What is Web3? And wonderfully, this is what made Web3Arabs grow so dramatically that it got more than 600 students in just one day during its launch on [Twitter](https://twitter.com/Web3Arabs).

Our plan to reach many students in MENA is by posting many advertisements on social media platforms, spaces, lives, and publishing valuable content that helps many learn about Web3 and start learning.

### How did you learn about the Livepeer Grants Program?

From [Ahmed](https://twitter.com/PeterPanYes)

**Comment by hansy** [comment]
Thank you for applying @KhairallahA! We'll get back to you with a decision with 2-4 weeks!

**Comment by hansy** [comment]
Hey @KhairallahA, we'd love to fund this project! Can you DM on Discord (@hansy_) so we can fine tune milestones together?

**Comment by KhairallahA** [comment]
@hansy Great news! Of course, I sent you a freind request from my account (@khairallah).

**Comment by hansy** [comment]
As per our conversation, here are the Livepeer-related topics you are interested in covering on your platform:

- Building a TikTok or YouTube application with Livepeer
- A project combining Lens Protocol and Livepeer

I'm queuing your upfront payment (20%); when it's confirmed I'll reply here with the tx receipt and the grant will be kicked off!

**Comment by hansy** [comment]
Hey here's the tx receipt for the upfront payment: https://arbiscan.io/tx/0xd49d080aaaf657d759ccc2a2a1aa7f40d35d0b386a3cb97d6549e655c4ccf77c.

With that, the grant is kicked off! The end date for the grant is **September 25, 2023**. Let me know if you have any questions!

**Comment by hansy** [comment]
Hey @KhairallahA! Here's the tx receipt for the completed grant: https://arbiscan.io/tx/0x9f1624a366b68c4b95f6d6b5776b97360f3fc63839e3e7c2dc338f9a55f09ecb. 

Great work! Let me know if you have any questions!
