### ISSUE TITLE
[Video Disruptors Grant]: 

### ISSUE THREAD

**Issue by KuadraTV** [livepeer/grants#174]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

This project addresses a crucial need – fostering an environment of unrestricted expression and preserving the essence of free speech for the youth of Barcelona. By using the Livepeer decentralized service, we will be able to establish ourselves as a truly independent web TV that will broadcast around the clock via a dedicated website. Our mission is to empower the upcoming generations in Barcelona to authentically articulate their thoughts and perceptions of the world around them. In a rapidly changing society, the need for unfiltered self-expression is more critical than ever, and twitch (our first option before knowing of Livepeer) doesn’t guarantee that. 
We are creating a platform for uninhibited communication, enabling the youth to share their unique perspectives and candidly discuss the realities they encounter daily. Through this endeavor, we aspire to curate a diverse range of content. Our web TV channel will showcase an array of original creations, encompassing captivating podcasts, thought-provoking reporting, enthralling DJ sets, electrifying concerts, spontaneous jam sessions, and even engaging cooking shows; all of this complemented with content from other local creators.
This project not only fulfills the need for a genuine platform of free speech but also promotes a sense of community engagement and collaboration. By harnessing the potential of livepeer's decentralized service, we ensure the unhindered flow of ideas and narratives, reinforcing the foundations of an open and empowered society. 

### Link to demo website (if applicable)

https://kuadra.works

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

It strategically positions Livepeer as the preferred solution within the context of evolving television trends. With traditional television corporations shifting towards digital formats or fading away, there exists a compelling opportunity for the rise of independent, community-managed TV networks. Our exploration of playout software reveals an emerging, underserved niche where existing options cater primarily to larger centralized networks, leaving accessibility and adaptability gaps for smaller users. This underscores the crucial role of Livepeer's technology, particularly considering the ongoing development of open-source playout solutions, and when user-friendly playout software starts surfacing, Livepeer will be the go-to. 
Successful execution offers the empowerment of community-driven TV networks, guaranteeing uninterrupted, high-quality streaming. Conversely, failure may come from content scarcity and compromised streaming quality, emphasizing the pivotal importance of meticulous playout software selection and the delivery of an exceptional user experience through Livepeer's service.

### Please describe in details what your final deliverable for this project will be.

Our ultimate deliverable for this project is a groundbreaking web television platform that offers an immersive social experience, deeply resonating with Barcelona's new generation. This platform aims to establish a strong sense of identification and connection between viewers and content, encouraging active participation in shaping its direction. By fostering a vibrant community, the platform enables users to express their thoughts and ideas, collaboratively generating diverse, culturally rich content. It operates around the clock, ensuring accessibility and convenience, while its unique approach prioritizes creative empowerment over corporate interests. In essence, our final software empowers Barcelona's youth to shape the future of television, embodying the city's creative spirit and harnessing collective creativity to revolutionize the media landscape.

### Please break up your development work into a clear set of milestones

(b) I use the term 'us' to refer to this project because the community plays a vital role in its future. However, I am currently working alone, learning to code a website and seeking solutions by engaging with people on forums.

Regarding (a):
- Our focus includes identifying suitable playout software capable of handling all TV content transmission. We are exploring options for a user-level solution.
- We are in the process of determining the costs associated with transcoding 43,800 minutes of content transmission. These costs will gradually increase, starting at a low point since we are a pre-startup. Our goal is to ultimately create a product available for subscription.
- We are actively developing a comprehensive Video On Demand (VOD) experience for subscribers. Currently, we are utilizing Google Drive, which serves our initial needs.

(c):
- Playout software costs vary based on specific requirements, ranging from $3,000 to $15,000 for professional software, and there are monthly subscription options reaching up to 200€.
- The expenses associated with the streaming service depend on decisions made by our representative team.
- While using Google Drive keeps costs low, we plan to transition to a decentralized and more customizable option, such as the one offered by Livepeer.

In essence, the expenses are influenced by the choice of Playout software and the cost of Livepeer services.

(d) The intention is to launch a preliminary beta on September 15th, but it could be easily postponed since the project is still under construction and hasn't been widely disseminated.

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

I would essentially prepay all the transcoding expenses for a year of uninterrupted streaming (pending a final price from your representative). Additionally, I would cover the expense for a VOD service capable of accommodating up to 2TB of video content, which will be accessed over time (subject to determination with various providers).

Approximately 10,000€ would be allocated for Livepeer services, while the remaining funds would be distributed among the following: playout license acquisition/developer hiring, hardware upgrades, and the acquisition of content-producing equipment. This includes a professional video camera to complement our existing equipment.

### Specify your team's long-term plans to maintain this software and upgrade it over time

We will initiate with a weekly program that will be gradually refreshed with new shows to replace the older ones.
The website will undergo continuous enhancement to provide a seamless experience and to foster community engagement through Discord and other social media platforms.
Should we achieve a stable final outcome and manage to attract investors, our objective will be to establish dedicated recording studios. This will provide creators with a dedicated space to produce their content, while also serving as a physical hub for hardware and recording equipment, separate from my residence.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

I am a technologically-oriented individual deeply engaged with the evolving future of my city, which is currently undergoing both positive and negative transformations due to the ongoing economic and technological shifts in society. I am committed to acquiring any necessary knowledge to ensure the success of my project, and for areas beyond my expertise, I am proactive in seeking out the right individuals to collaborate with. Currently, I am capable of handling the project independently. While I do consult friends and forums for insights, feel free to reach out to me directly if you wish to learn more about me or my endeavors. I am readily available for contact at any time.

### Who is your target user group? How do you plan on getting your users to use this?

Targeting individuals between the ages of 18 and 40, our aim is for this platform to ignite fresh perspectives in a multi-generational manner, with a primary focus on the youth. They hold the key to ushering in the next phase of our rapidly evolving society.

To reach our target audience, we will begin with local marketing efforts such as posters, stickers, and word-of-mouth promotion. Subsequently, we will extend our reach through social media advertising and establish a physical presence at key city events.

### How did you learn about the Livepeer Grants Program?

Alex, one of your representatives was kind enough to send me the link while we were discussing about pricing.
He was very gentle!

### Was this project started at a hackathon or another web3 event? Which one?

It began during the quarantine when I organized in-house live streams featuring various DJs who had no clubs to perform at.

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

If the project is not eligible for a grant, I am still willing to contribute to Livepeer in any way I can be of assistance. It would be ideal to work for such a crucial component of the project.

**Comment by hansy** [comment]
Thanks for applying @KuadraTV! We'll get back to you with a decision within 2-4 weeks!

**Comment by hansy** [comment]
Hey @KuadraTV, we'd love to fund this project! Can you DM me on Discord (@hansy_) so we can fine tune the milestones together?

**Comment by hansy** [comment]
Hey @KuadraTV, we'd love to fund this project! Can you DM me on Discord (@hansy_) so we can fine tune the milestones together?

**Comment by KuadraTV** [comment]
Sure! I’ll contact you now!

Thank you
