### ISSUE TITLE
[Video Disruptors Grant]: Live Cinema

### ISSUE THREAD

**Issue by divineinferno** [livepeer/grants#175]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

H&N is a leading immersive experience company on the blockchain and we are pioneering a genre of film called Live Cinema. These are films that are shot, performed, and edited live and only experienced in real-time via live streaming. Our past two films are critically acclaimed with premieres at major festivals like Raindance Film Festival and CPH:DOX and we are currently in production for our next feature film to be streamed in early December. We are looking to utilize Livepeer for our upcoming live film experience and subsequent productions.

Audiences are growing less engaged with more traditional forms of storytelling. Cinema is dying and Tik Tok is thriving. We are applying for a video disruptors grant to implement and test live streams into our workflow for both home and cinema audiences.

### Link to demo website (if applicable)

https://hereandnow.events/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Our last two proof of model projects, In the shadows it waits, and Those Left Waiting premiered at top tier film festivals like Raindance and CPH:DOX, being viewed by over 10,000 people. 10,000 x 120 minutes = 120,000 minutes of live streamed content.

As we embark on this journey, and grow as a company, we also want to start inviting other directors and content creators to work with this genre of Live Cinema. This includes not just highly produced feature films, but also short form content as well.   

Live streaming has an inherent risk to it, but that’s also what makes it so special. It’s important for us that we build a strong relationship with a company like Livepeer to encourage and develop ‘Live Cinema’. 

### Please describe in details what your final deliverable for this project will be.

We acknowledge the uniqueness of this project as a grant proposal, but we believe that the true value of this proposal lies within the actual process of making and then delivering the film. While our primary objective is to create an impressive live stream event, it's essential to recognize that the entire process itself is a valuable deliverable. There will be a large amount of PR surrounding the film. We would be delighted for Livepeer to be linked with our journey, as we plan to share regular updates about our process through social media. This will allow us to showcase how Livepeer empowers us to bring our innovative live films to fruition.

We are happy to discuss this further as there might be other opportunities to highlight Livepeer that we are missing.

Deliverables:
- A feature film, shot, performed, and watched live using Livepeer. 
- Live film trailers
- Technical runs & rehearsals
- Q&A sessions using Livepeer
- Social Media posts highlighting our usage of Livepeer over the next three months leading up to our film. 

### Please break up your development work into a clear set of milestones

**1. Technical Experimentation:** 
Full Live stream test with Black Magic Camera Studio Cinema gear, transcoders and encoders and Livepeer. 
A small team of filmmakers and technicians working on this milestone.
4 week completion by October 1st.

**2. Full Technical Rehearsal & promotions:** 
Live Stream rehearsal, trailer and promotional material. 
Directors, Producer, PA, Gaffer, camera operators, sound technicians, editor and performers. 
4 week completion by December 1st. 

**3. World premier:** 
Live streamed feature film & Q&A with cast and crew. 
Directors, Producer, PA, Gaffer, camera operators, sound technicians, editor and performers. 
December 1-3rd.

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

**- Technical Experimentation**
Cameraman: $1000
Editor: $500
Gear (camera, encoders/transcoders, wireless transmitters):  $1000
SUB TOTAL: 2500

**- Full Technical Rehearsal & promotional material**
2x Cameraman: $2000
Editor: $500
Gear (cameras, encoders/transcoders, broadcaster, lighting, sound) : $2000
SUB TOTAL: 4500

**- World premier & live stream delivery** 
2x Cameraman: $2000
Editor: $500
Live Director: 1500
Live Producer:1500
Gear (cameras, encoders/transcoders, broadcaster, lighting, sound): $2000
SUB TOTAL: 7500

**TOTAL: 14,500**

### Specify your team's long-term plans to maintain this software and upgrade it over time

We want to become the premiere company for delivering ‘live cinema’ experiences. Our long term plan is to be building exclusive film experiences that are live streamed to large audiences around the world with our novel format. 

We have a three year plan with multiple projects in the pipelines ready for further development and production and we’d love to build a strong relationship with a decentralized streaming protocol with Livepeer. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

**HERE & NOW**
We are a group of artists who take culture seriously; we are curious about what virtual experiences can do, and have fun doing it. As professional immersive and film directors with over 20 years shared experience we have dedicated our lives to creative pursuits. Our films and experiences are critically acclaimed for their innovative approaches and have been honored to be nominated and showcased on some of the world's biggest stages including the Venice International Film Festival, Cannes, TIFF and many others.

**Michael Beets**
Beets is an award winning director and pioneer of live films. His film and experiences have been screened at festivals around the world including Venice Film Festival, Cannes, Busan, and Toronto International Film Festival. Beets is the creative force behind the much loved and successful HERE & NOW interactive experiences.

**S.C. Wilson**
S.C is an award-winning actor and filmmaker. His various film works have appeared in festivals around the world. His feature documentary, A thousand miles to get your head straight was released in June, 2023 in partnership with GoPro and Stab surf magazines, and his debut feature film Miles away received an AU/NZ distribution offer and is in the final stages of post-production.
https://hereandnow.events/
info@hereandnow.events

### Who is your target user group? How do you plan on getting your users to use this?

We have built a preexisting community and audience in the web3 space over the past 2 years. We have over 4000 collectors who are actively engaged with our virtual experiences. It is now time to take our product to a mainstream audience. We see this as a groundbreaking and industry disruption model which can be adopted by creators and filmmakers. 

We are interested in capturing content creators, filmmakers, and audiences interested in novel live experiences. 

### How did you learn about the Livepeer Grants Program?

We have a project highlighted through Radar (culture3) on the 21st August. They informed us about Livepeer. 

### Was this project started at a hackathon or another web3 event? Which one?

No.

**Comment by hansy** [comment]
Thanks for applying @divineinferno! We'll have a decision for you within the next 2-4 weeks!

**Comment by hansy** [comment]
@divineinferno Here's the tx receipt for the upfront payment: https://arbiscan.io/tx/0xeada4e575e5f3bb49bfaf8c43786c752e9f382e7c983c46643ea5747f2740b1e!
