### ISSUE TITLE
[Video Disruptors Grant]: StationX.network

### ISSUE THREAD

**Issue by toshitsom** [livepeer/grants#176]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

**StationX is a protocol to automate workflows for communities.** 

Using StationX, anyone can:
- Start collecting contributions in stables or native currencies into a multi-sig treasury
- Issue ERC20 or NFT based memberships for use cases like on chain Syndicates, VC DAOs, NFT Collectives, Alpha Chats, etc.
- Automate day-to-day operations to manage treasury (distributing funds, buy/sell NFTs, manage funding rounds, etc) and members (gating members, rewarding, etc).

**Problem:**
The biggest challenge that communities face today is getting work done seamlessly. They have to manage multiple tools like Snapshot for voting, SAFE for Treasury management, etc, which are not connected to each other. So coordination becomes very difficult. We want to solve this problem.

With StationX, communities will now be able to manage everything at one place. People can easily connect their existing SAFE multi-sig or create a new one & use the built-in governance or connect with Snapshot. Know more about StationX [here](https://www.youtube.com/watch?v=WwIGpRWwyAk).

### Link to demo website (if applicable)

https://app.stationx.network

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

The biggest challenge that communities face today is with member engagement & participation.

With Livepeer, we would enable communities on StationX to easily do token gated video conferencing & content streaming which would help them increase member engagement & attract more members.
- With token gating video conferencing, connecting with other community members & discussing ideas, strategies, etc becomes easier which would lead to increase in member engagement (raising proposals, voting, etc)
- Token gated content (live or pre-recorded) opens up many new avenues for communities to attract new members to join their community (exclusive content that is only available to the members of a community).

As the number of communities live on StationX increase, the number of people using Livepeer would also increase and since a person is part of multiple communities, more communities would start exploring & using Livepeer.

### Please describe in details what your final deliverable for this project will be.

Through our integration with Livepeer, we would enable:

1. Token(s) gated live and pre-recorded content.
2. Token(s) gated multiple user video conferencing.

### Please break up your development work into a clear set of milestones

**Milestone 1: Token gated live and pre-recorded content**
1. Estimated date of completion: 3 weeks (est. 21st September, 2023)
2. Budget: $10,000
3. Number of Devs: 3 (2 backend + 1 frontend)

**Milestone 2: Token gated multiple user video conferencing** 
1. Estimated date of completion: 3 weeks (est. 12th October, 2023)
2. Budget: $5,000
3. Number of Devs: 3 (2 backend + 1 frontend)

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Total requested budget - $15,000
- After passing of the grant - $5,000
- After completion of milestone 1 - $5,000
- After completion of milestone 2 - $5,000

The budget will be used for Development & integration with Livepeer 

### Specify your team's long-term plans to maintain this software and upgrade it over time

We plan to maintain & upgrade StationX over time.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

4 of us with CS backgrounds, ran a marketing & tech services company in India right after university from 2019 to 2021. We started building StationX in Early 2022.

[Rishav](https://twitter.com/0xrishavb) - CEO used to invest in crypto since 2017 (started with investing in projects through small pools & communities that had allocation with private investors). Invested in over 30 projects, this is where he first encountered the problem. Found out small communities came together to act as micro VCs, funds, and syndicates.

[Subham](https://twitter.com/subhamsengupta_) - CTO, has more than 6 years of experience in development & 2+ years of experience writing Smart Contracts. He has worked on multiple projects for clients ranging from retail, e-commerce, universities to build applications for custom use cases.

[Pranav](https://twitter.com/yeradaoti) - CMO, has more than 3 years of experience in product design, community & marketing. He started working with Web3 projects in mid-2021 and worked with over 10 projects to build their community.

[Toshit](https://twitter.com/toshitsom) - COO, is a performance marketeer with more than 3 years of experience in marketing & operations, worked with web3 projects since mid-2021 to generate traction & helped them with getting investors & partners on board.

### Who is your target user group? How do you plan on getting your users to use this?

Our initial target group is Investment Clubs, Syndicates, VC DAOs & NFT gated communities. 

We're currently in private Beta with 10 communities, closely working with them to improve the user experience & understanding their requirements before our Public Beta launch in late Q4 2023. 

Over 20,000 people have signed up for the Public Beta access. 

### How did you learn about the Livepeer Grants Program?

Livepeer team - Alex Mexicotte & Eric Tang

### Was this project started at a hackathon or another web3 event? Which one?

No

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

- On testnet, 150K+ people created Stations & 190K+ users have used StationX to claim USDC.
- On Polygon Mainnet, $100K has been pooled by a DAO to fund deals and CFJ (Venture DAO) is using StationX to activate NFT tier based memberships for their community.

**Comment by hansy** [comment]
Thanks for applying @toshitsom! We'll get back to you with a decision with 2-4 weeks!

**Comment by hansy** [comment]
Hi @toshitsom, we'd like to offer $4k to fund this project! We'd also like to offer an additional $1k as a success bonus for showcasing the Livepeer integration in your application to your community. Happy to brainstorm ideas with you and your team on ways to achieve that.

If this works for you, let me know! Feel free to DM me on Discord (@hansy_) and we can work through the details there!

**Comment by hansy** [comment]
Hey team, wanted to check up on the status of the grant?
