### ISSUE TITLE
[Microgrant]: 

### ISSUE THREAD

**Issue by fqclean** [livepeer/grants#177]
### What is your project, and what problem does it solve?

I am writing this grant request to have my submittal reviewed for a project plan to integrate API into my existing app that is not listed on the app store. Previous Integration with my app is Tatum's wallet API and Tangems API; it is hoped with this grant a Livepeer APi can be integrated and we can move to the next stage of development. 

### How is Livepeer used for this project?

Livepeer will be used to post video as a catalogue in the app which users will like or subscribe, or support another user.

### How will you improve your project with this grant? What steps will you take to meet this objective?

My existing Project is crytpo enabled the Livepeer integrate will help in the following ways

1) Give users Profiles the ability to share video 
2) Have streamed content from the Livepeer network without bandwidth responsibility 
3) A viewer for video's uploading to subscribe and support other users

### Was this project started at a hackathon or another web3 event? Which one?

n/a

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

My team and I have worked on apps for 4 years, they are a team very capable to fulfill every request I have given them. They have 1000's of projects and 1000,000's of hours I have always been pleased and know this integration API will be a success  for my app and Livepeer. 

### What is the project’s expected deliverable at the conclusion of the grant time period?

Video integration for users to interact with on there device 

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

The vision for my deliverable is to build support for users to grant recognition of skills and talents in there local community. This API will build a LPT donation for users to rate skill set gone will be the says of like/dislikes it will be a LPT value associated with the video. 

### How will this deliverable benefit the Livepeer ecosystem?

the branding will allow users to associate livepeer with video views 

### Who is your target user group? How do you plan on obtaining them?

This demographic will be a crypto centric audience can range from 10 - 80 depending on how involved they are in crypto. 

### How did you learn about the Livepeer Grants Program?

I previously was an applicant and am summitting this for a different functionality with my existing app.

**Comment by hansy** [comment]
Thanks for applying @fqclean! We'll get back to you within 2-4 weeks with a decision!

**Comment by fqclean** [comment]
Awesome I think this is a great opportunity to uplift the LPT ecosystem!

Enjoy your weekend

**Comment by hansy** [comment]
Hi @fqclean, what app are you looking to integrate Livepeer into? Can you share more details about it (including any links, if possible)? Have you launched with users?

**Comment by fqclean** [comment]
My project and app are not currently in the app store, the modification to
I corporate livepeer will bring an exiting dynamic, I had tatum.io
integrated as a wallet so that will allow users to interact in lpt token.
Follow up if you want to see or install the app, it currently uses NFC
technology so without that profile built access can't be granted. Thanks
for reaching out.
