### ISSUE TITLE
[Microgrant]: Giottus Livepeer(LPT) Listing Proposal 

### ISSUE THREAD

**Issue by Mohangio** [livepeer/grants#178]
### What is your project, and what problem does it solve?

Giottus is a crypto platform that provides a solution to the problem of enabling Indian users to buy and sell Livepeer (LPT) tokens using Indian Rupees (INR).

Giottus solves the problem of access and liquidity for Indian users interested in trading Livepeer (LPT) by offering a trading platform where users can exchange their Indian Rupees (INR) for LPT tokens and vice versa. This platform provides a secure and convenient way for users in India to participate in the Livepeer ecosystem and take advantage of the potential benefits offered by this blockchain project.

### Link to demo website (if applicable)

https://www.giottus.com/

### How is Livepeer used for this project?

Giottus will list Livepeer INR and USDT pair and enable ERC20 Withdrawal and Deposit 

### How will you improve your project with this grant? What steps will you take to meet this objective?

We have several key objectives in mind, including listing the Livepeer token (LPT), enabling ERC-20 withdrawal and deposit functionality, and conducting marketing and trading contests to engage and educate users. 

Here are the steps we will take to achieve these objectives:

Listing Livepeer Token (LPT): The grant will be used to facilitate the listing of Livepeer (LPT) on the Giottus exchange. This involves technical integration, compliance checks, and ensuring that LPT trading pairs with INR are available on the platform.

Enabling ERC-20 Withdrawal and Deposit: To enhance user experience and flexibility, we will use the grant funds to implement ERC-20 withdrawal and deposit functionality for Livepeer (LPT) tokens. This will allow users to seamlessly transfer LPT in and out of their Giottus wallets using the Ethereum-based ERC-20 standard.

Marketing Initiatives:  We will allocate a portion of the grant to marketing efforts aimed at increasing awareness of Livepeer and the trading opportunities available on Giottus. 

Trading Contests: To engage and incentivize our users, we will organize trading contests specifically focused on Livepeer (LPT). These contests will encourage users to actively trade LPT on the platform, boosting liquidity and participation. Prizes, rewards, and recognition will be offered to top performers, further driving interest in Livepeer trading.

### Was this project started at a hackathon or another web3 event? Which one?

We are a bootstrapped organization that started five years ago. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Our team at Giottus boasts a wealth of experience and a proven track record in the cryptocurrency and blockchain industry, which makes us the ideal choice to execute this project. We have successfully listed over 210 projects in INR trading pairs, establishing ourselves as a prominent exchange in India's cryptocurrency landscape. This extensive experience has honed our expertise in technical integration and compliance procedures, ensuring that the listing of Livepeer (LPT) on our platform will be seamless and fully compliant.

With a user base exceeding 1.3 million individuals in India, we have a deep understanding of the Indian market's dynamics and the unique needs of our users. This user-centric perspective guides our approach to project execution, guaranteeing that we can effectively cater to the demands of the Indian Livepeer community.

Furthermore, our past collaborations with prominent blockchain projects like Near, Algorand, Tomochain, Flux, and Tethergold have equipped us with the knowledge and insights required to provide comprehensive listing and marketing support. We have a proven history of successfully promoting and facilitating the trading of cryptocurrencies.

Team Profile 
Arjun Vijay Co-Founder: https://www.linkedin.com/in/arjunvijay89/
Website: https://www.giottus.com/

### What is the project’s expected deliverable at the conclusion of the grant time period?

**Our execution will follow these major categories:**

1. Awareness campaigns on socials.
2. Trading contests that will incentivise traders to trade and use Livepeer (LPT)

Giottus, as a crypto exchange, has the following processes (tested strategies) ready to be executed to maximise the number of users interacting with Livepeer (LPT)

**Internally,**

1. We will send an internal mail to our customer base announcing the successful listing of Livepeer (LPT) and how it can be utilised. 
2. We will enable recurrent push notifications to our customers.
4. Display banner messages on the app and web version.
5. We will write articles about the basics of Livepeer (LPT), how the LPT tokens can be purchased, and how to use networks for LPT transfers (Giottus official blog, medium article).
6. Social media promotions (image posters, polls, video posts through Youtube, Telegram, Twitter, Facebook, LinkedIn) in the form of giveaways.
7. AMA with key people from the Livepeer (LPT) team.

**Externally**,

1. We will collaborate with social media influencers in top Indian regional languages on an overview of Livepeer (LPT) and trading via Giottus using INR/USDT pairs (The cost will be incurred by the Livepeer (LPT) team separately and get directly paid to the influencers).
2. We will target users across India and will fall between the age group of 25 to 40 who have an online presence on Twitter, Telegram, and mainly Youtube. We have a list of influencers that we regularly work with who give us a higher ROI on action points that we seek. 

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

After the project listing, we want users to trade for investment purposes and transfer LPT for DeFi purposes.

### How will this deliverable benefit the Livepeer ecosystem?

Livepeer is listed on the Indian exchange in INR pair and users trade easily using local fiat.

### Who is your target user group? How do you plan on obtaining them?

Indian Crypto Investor/Trader/Web3 Enthusiasts.

### How did you learn about the Livepeer Grants Program?

We have learned about Livepeer Grants via Livepeer's official website and check out GitHub for grant details.

### What's your wallet address?

0x831ce13a399b61e59698b974a5ec0c5c11bade1e

**Comment by Mohangio** [comment]
@hansy Thank you! I look forward to your reply

**Comment by hansy** [comment]
@Mohangio thank you again for applying. However, at this time we've decided not to fund this proposal. Please feel free to apply again in the future; we look forward to seeing your project's continued progress and growth!
