### ISSUE TITLE
[Video Disruptors Grant]: Refraction

### ISSUE THREAD

**Issue by rafkats** [livepeer/grants#181]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

We believe culture and curated quality content are powerful drivers for wider adoption. At large,  platforms have largely focused on the tech and not enough on the content that will not only draw people in, but retain attention and increase interaction and usage. There is a need for a creator-driven platform that delivers quality curated content for the audience, and implements features that creators are looking for, built from the ground up and shared with an audience that is primed for disruption. 

Refraction’s strong curatorial pedigree, engaged creative community of over 1000 global artists and cultural operators, world class IRL events and experiences, and distributed network of cultural partners uniquely position us to build the video streaming platform built from the ground up that will inspire and engage creators to use Livepeer, as well as drawing audiences in with quality content, introducing both communities to the power of decentralized streaming and what the blockchain can do as a creative tool and as a support mechanism for a more equitable creative industry. 

### Link to demo website (if applicable)

https://www.figma.com/proto/B0h66SQ9YXuoUyxndIdbqA/Refraction-Website-2.0?page-id=211%3A4022&type=design&node-id=632-110136&viewport=1452%2C-2237%2C0.1&t=XQ16QdiaiGAzdVhx-1&scaling=scale-down&starting-point-node-id=632%3A110136&show-proto-sidebar=1&mode=design

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Benefits: Successfully launching this video platform means a passionate and engaged crowd discovering not only the future of live streaming through Livepeer, but the power of web3 as a tool to support and engage with creators on a new level - and the potential to empower creators, new creative tooling, and the importance of autonomy and deplatforming through decentralized infrastructure. 

Risks: If the technology and implementation/experience is not smooth, we risk further alienating the audience, contributing to a narrative of web3 being complicated, too early, or just a fad. 

Challenges: As we are building from a creator-first perspective, it is currently unknown if all features would be possible with current technology, and if not, how certain features could be implemented from a technical perspective should they be necessary. 

### Please describe in details what your final deliverable for this project will be.

We will build a creator-led live streaming platform that will live on the Refraction website as part of our creator ecosystem. This platform will showcase original content from our community (eg. archival, live streams from events, prerecorded content specifically created for the platform.) We will research audience interaction on the blockchain in ways that, and do a prototype, will be determined during the process. We will also look at implementing Universal Data Licensing as well as other features that benefit the creator. 

### Please break up your development work into a clear set of milestones

Phase 1: Discovery - 2 weeks

Introduce members of the Refraction community to available Livepeer tooling and apps and engage Livepeer’s broader dev community to introduce Livepeer tech - and suggest changes which will informed by the needs of creators.

Output: Onboarding sessions with a select group of creators where we cover what’s available through Livepeer with the aim of using the tools for a specific creative output as well as identifying what is missing from the current ecosystem. What would drive more video streaming on the Livepeer network that is also web3 value aligned. 

Milestone: Research report on strengths and whitespaces within the current Livepeer ecosystem informed by a creator perspect. This will inform the next phase of building. 

Phase 2: Development - 4 weeks

Document and apply learnings from the Discovery phase to improve existing tech or create a net new experimental product. 

Output: Improvement of existing tech or creation of a net new artist-focused tool for the Livepeer ecosystem. Working prototype of a creator-led product to be tested by the community. 

Phase 3: Testing & Refinement - 3 weeks

Creators will use the tool over a period of time and experiment with creating and sharing new work etc. with opportunity for capturing feedback. This feedback will help Livepeer developers further customize the prototype to meet creator needs. 

Output: Each artist will be commissioned to create new work using the tool. The work will then be aggregated and showcased on Refraction’s platform once launched.  

Phase 4: Platform integration 2-weeks

Explore how the creative output could live on the upcoming Refraction platform
Output: Development support to finalize a player/showcase for content created in the larger program that live on Refraction’s upcoming creative platform. 

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

15K Total 
Project Manager / Researcher (3 months, 6h/week) – $2,400 (oversee project, work closely with community manager and developer to plan and execute creator-led research program and testing, organize research)
Artist Relations / Community Manager (3 months, 6h/week) – $2,400 (coordinate community outreach, gathering and documentation of insights)
Developer (2.5 months, 8h/week) – $5,000
Marketing / Content Manager (1 months, 4h/week) – $600
Artist Participation Incentive/video production – $4,200
ARweave Storage – $400 (approx. 111GB of video)

### Specify your team's long-term plans to maintain this software and upgrade it over time

This will be a content pillar on our website and would serve as a major vertical, we plan on not only maintaining the software but also further developing it as it has potential to be an integral part of our ecosystem. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Graham Bertie (Toronto, Canada) - Developer
Anbar El Mokri (Marrakech, Morocco) - Project Manager
Malcolm Levy (Toronto, Canada) - Curator Artists Relations
Raf Katigbak (British Columbia, Canada) - Marketing/Content

### Who is your target user group? How do you plan on getting your users to use this?

Our target user would be creators and artists at the emerging and established level of their careers. They have a following and collector base that would support the reach of the platform. They have some experience creating video content and or performing live. 

### How did you learn about the Livepeer Grants Program?

Through Shannon Wells, Head of Ecosystem Growth. 

### Was this project started at a hackathon or another web3 event? Which one?

No

### Do you consent to using "Powered by Livepeer" watermark on your application?

- [X] Yes
- [ ] No

**Comment by hansy** [comment]
Here's the upfront payment tx receipt: https://arbiscan.io/tx/0x7eb4e55e8763d4ec8a7e32f252c8c5965f93e4810cfb79640af3169d83ba2a25. 

Additionally, below are the Milestones along with their amounts and timelines:

Phase 1: Discovery - 2 weeks (29 Sept – 13 Oct): 15% $2250
Phase 2: Development - 4 weeks (13 Oct – 13 Nov) 30% $4500
Phase 3: Testing & Refinement - 3 weeks (13 Nov – 4 Dec) 20% $3000
Phase 4: Platform integration 2-weeks (4 – 18 Dec) 15% $2250
