### ISSUE TITLE
[Video Disruptors Grant]:  video film education and Game 

### ISSUE THREAD

**Issue by axlywb** [livepeer/grants#182]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

our community with a background of designers grafis and development meta, build game. Community local artists,
that will allow for some creativity. we will make a AR/VR animated film video with educational

1. The problem that we will overcome is that many films become political campaign events, etc. Films for children should not be in that realm
2. we create an educational space through entertainment for children.

Many of them feel lonely because their parents are busy. who doesn't make time for their children.
therefore we want to overcome this too

### Link to demo website (if applicable)

https://www.bonfire.xyz/GLADIESNEY/365325080-823272549591097-8137195961368032667-n

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

benefits for the LPT ecosystem. we will save our videos permanently on the livepeer chain. streamer on chain
 Our goal is education and entertainment

### Please describe in details what your final deliverable for this project will be.

making animated avatar creator video

### Please break up your development work into a clear set of milestones

Designer grafis and developer
📌desember 7 2023

## Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.
 
Designer grafis $5000
development $5000
Marketing launching $2000

funding  $12,000 USD

Ethereum / Arb wallet 
0x22b62684B043fB949B0d8924C596f70B39669026

### Specify your team's long-term plans to maintain this software and upgrade it over time
-

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

background of the designer team Meta labs and aims to educate through animated film videos and games

### Who is your target user group? How do you plan on getting your users to use this?

Our target is that there is no age limit but it is very good for children

### How did you learn about the Livepeer Grants Program?

from Google. after searching for a solution

### Was this project started at a hackathon or another web3 event? Which one?

web3 lainya

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.
We hope to contribute and be accepted by the LivePeer team as we have been trying in the last week to be some part of the collaboration with avatar companies etc

### Do you consent to using "Powered by Livepeer" watermark on your application?

- [X] Yes
- [ ] No

**Comment by axlywb** [comment]
please for support

**Comment by axlywb** [comment]
milestones
1.vr designer
2.Development and launch
3. marketing

It's not written down, but more importantly we need equipment

for discussions etc via my Twitter and I have followed your Twitter.
https://twitter.com/AxlyWB

**Comment by hansy** [comment]
Thanks for applying @axlywb. Unfortunately at this time, we have decided not to fund this project. But please feel free to apply in the future with more updates and progress!

**Comment by axlywb** [comment]
okay thanks. I will keep working on this project. even though it's not right for now

**Comment by axlywb** [comment]
we have updated this proposal and we have become part with AR meta.

Can this proposal be considered?

**Comment by axlywb** [comment]
we build AR and meta will develop AI and we focus on AR only

**Comment by axlywb** [comment]
This application is discontinued for now.
because the team will build a web3 version of TikTok and a discussion room

and this educational mission will continue to be built in the future
