### ISSUE TITLE
[Microgrant]: Learn and Create on LivePeer in Spanish for LatAm

### ISSUE THREAD

**Issue by cristpereirag** [livepeer/grants#183]
### What is your project, and what problem does it solve?

Colledge's "Learn and Create on LivePeer '' program is the gateway to mastering Livepeer's technology. We equip all levels of users, from beginners to experts, with the knowledge they need. By closing the education gap through specialized webinars and workshops, we cultivate a skilled community, driving Livepeer's growth. In Latin America, we tackle the blockchain knowledge deficit, stimulating innovation and economic growth. Our distinguished blockchain-focused programs don't just educate but empower, providing practical tools to thrive in the LivePeer and blockchain ecosystem. Colledge is leading the way in shaping blockchain education and success in Latin America.

### Link to public GitHub repo (if applicable)

https://www.github.com/somos-colledge

### Link to demo website (if applicable)

https://www.colledge.social

### How is Livepeer used for this project?

Our educational program 'Learn and Create on LivePeer' will be based on the necessary technologies for programmers to use LivePeer for application development. With a 12-hour theoretical content and 12 hours of hands-on practice, students will gain a solid understanding of LivePeer. Additionally, as our program will be conducted virtually, we will leverage the LivePeer protocol to stream the content, demonstrating its real-time content distribution capabilities.

### How will you improve your project with this grant? What steps will you take to meet this objective?

This educational program presents a unique opportunity to elevate and expand our blockchain education initiatives, with a special focus on LivePeer, in Latin America. Our primary objective is to create a comprehensive LivePeer program that equips students with the essential knowledge and practical skills required for application development using LivePeer's technology.

To achieve this, we plan to take the following steps with the grant:

1. Curriculum Development: We will allocate a significant portion of the grant to develop an extensive introductory and advanced LivePeer curriculum, ensuring that it covers all necessary topics comprehensively.

2. Increased Accessibility: A portion of the grant will be invested in making the program more accessible by offering open and recorded content on our platform, thus reaching a wider audience across Latin America.

3. Practical Application Focus: We will prioritize hands-on experience by structuring our program around practical LivePeer application development, allowing students to build real-world use cases.

4. Community Building: Part of the grant will go towards fostering a vibrant community of blockchain enthusiasts and professionals through educational initiatives, networking events, and support for collaborative projects.

With this grant, we can successfully launch and sustain this educational program, enabling both programmers and users to grasp LivePeer's protocol intricacies while mastering application development. Our steps will ensure that the program's objectives are met effectively, furthering blockchain adoption and entrepreneurship in the region.

### Was this project started at a hackathon or another web3 event? Which one?

No

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Cristóbal Pereira, CEO:
Cristóbal brings a wealth of experience in blockchain education and entrepreneurship. He has a proven track record of leading successful educational initiatives in the blockchain domain. His extensive network and leadership skills make him an ideal CEO to drive this project.

[LinkedIn](https://www.linkedin.com/in/cpereirag/)
[Twitter](https://www.twitter.com/cristpereirag)
[Github](https://www.github.com/cristpereirag)

Alejandra Pacheco, Partners & Incubator Lead:
Alejandra's background in fostering blockchain startups and partnerships is invaluable. Her experience in supporting and incubating blockchain projects positions her as a key contributor to building a thriving LivePeer community.

[LinkedIn](https://www.linkedin.com/in/alepachecom/)

Paulina Espinoza, Academic Manager:
Paulina's expertise in curriculum development and educational management ensures the high quality of the courses offered. Her background in education and blockchain is instrumental in shaping the learning experience.

[LinkedIn](https://www.linkedin.com/in/paulinaec91/)

Amelia Arias, Operations Manager:
Amelia's operational prowess keeps the project running smoothly. Her meticulous organization and management skills are crucial for the successful execution of educational initiatives.

[LinkedIn](https://www.linkedin.com/in/ameliarias/)

Antonio López, CTO:
Antonio's technical expertise and experience in blockchain development are essential for the successful implementation of LivePeer-related projects. His leadership in technical matters ensures a strong technical foundation.

[LinkedIn](https://www.linkedin.com/in/antoniojlopez)

Cristian Vélez, Front End Developer:
Cristian's skills in front-end development enhance the project's ability to create user-friendly platforms. His contributions are key to providing accessible educational content and community engagement.

[LinkedIn](https://www.linkedin.com/in/cristian-velez-arbelaez-131b66206?originalSubdomain=cl)

With this diverse and experienced team, we are well-equipped to develop and execute the "Learn and Create on LivePeer" project, combining technical knowledge, educational expertise, and a strong network in the blockchain space.

### What is the project’s expected deliverable at the conclusion of the grant time period?

At the conclusion of the grant time period, our project will deliver a robust set of resources and initiatives designed to empower individuals in Latin America with the knowledge, skills, and support needed to thrive in the LivePeer blockchain ecosystem. Our commitment to accessibility and community-building underscores our dedication to fostering blockchain entrepreneurship within the LivePeer framework in the region. These expected deliverables include:

1. Educational Content: We will provide a comprehensive library of educational materials in Spanish, featuring video tutorials, supplementary materials, guides, and documentation. This content will be accessible to all interested individuals and will cover LivePeer and related blockchain topics extensively. Specifically, we will offer a minimum of 12 hours of free educational content in Spanish on using and developing applications on LivePeer for at least one year.

2. Dedicated Website: We will launch a dedicated website that serves as a centralized platform to promote and facilitate access to our educational offerings and community engagement initiatives. This website will house our entire content library for a minimum of one year, providing information, course registration, and a platform for community interaction.

3. Community Events: To foster a thriving blockchain community in Latin America, we will organize and participate in a minimum of two events in the countries with the highest student registrations within the region. These events will include workshops, webinars, and networking opportunities for knowledge sharing and collaboration.

These deliverables will leave a lasting impact on the blockchain education landscape in Latin America, enabling individuals to become proficient in LivePeer and actively participate in the blockchain ecosystem.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

The core mechanic we aim for participants to achieve, at the conclusion of each course, is the ability to:

1. Configure and Manage Livepeer Nodes: Participants should be able to proficiently configure and manage their own nodes on the Livepeer network, ensuring secure and efficient operations.

2. Perform Video Transcoding: Participants should grasp the process of video transcoding using Livepeer and be capable of applying this knowledge effectively in practical scenarios.

3. Integrate Livepeer into Applications: Participants should possess the skills to seamlessly integrate Livepeer technology into their own applications and projects related to live video streaming.

4. Upload and Mint Video NFTs: Students will learn how to upload and mint video NFTs, expanding their practical expertise and enabling them to explore new opportunities in the blockchain and content monetization space."

This addition highlights the valuable skill of uploading and minting video NFTs, further enhancing the capabilities of participants in the blockchain ecosystem

### How will this deliverable benefit the Livepeer ecosystem?

The program “Learn and Create on Live Peer” will not only increase understanding and knowledge of the technology, but will also contribute to growth, stability and innovation within the Livepeer ecosystem. In addition, it will foster an active and educated community that can help maintain and improve the ongoing network.

Here are some highlights tha will benefit Livepeer ecosystem through program deliverables:

1. Oriented to a variety of profiles, from those who want to understand the fundamentals of Livepeer, people looking to become node operators and application developers using Livepeer technology. This can lead to increased network stability and performance, which is critical to Livepeer's success.

2. Increased Livepeer Adoption: Accessible, high-quality training removes barriers to entry for new users interested in using Livepeer. This can result in increased adoption of Livepeer technology in a variety of applications, which will strengthen and expand the ecosystem.

3. Innovation and Application Development: Developers educated in the use of Livepeer will be better prepared to create applications and projects that leverage Livepeer's video transcoding technology. This can lead to the creation of a variety of innovative services and applications that utilize the Livepeer network.

4. Promotion and Dissemination: As students gain skills and knowledge about Livepeer, they are likely to share their experience and promote the technology in their networks and communities. This can generate greater awareness and attraction to Livepeer, which will benefit the entire ecosystem.

5. Active Educational Community: The formation of Colledge creates an active educational community of informed users and participants who can help other new users and contribute to the continued growth of the Livepeer ecosystem.

6. Technology Improvement: As more developers work with Livepeer, feedback and contributions to improve the technology are likely to emerge. This can lead to updates and improvements to the Livepeer network in response to community needs.

7. Attracting Companies and Entrepreneurs: Specialized training can attract companies and entrepreneurs interested in Livepeer's technology. These players can invest in the technology and use it for their own projects and services, which would strengthen the ecosystem and increase its usefulness.

### Who is your target user group? How do you plan on obtaining them?

The target students for the “Learn and Create on Live Peer” program in collaboration with Livepeer can include a variety of profiles, from those who want to understand the fundamentals of Livepeer, people looking to become node operators and application developers using Livepeer technology. Here's a breakdown of potential target students and how they might be reached:

- Blockchain Developers and Live Video Developers: these students may be interested in learning how to integrate Livepeer technology into applications and projects related to live video streaming. They can be reached through:
  - Announcements in blockchain developer communities.
  - Promotion of technology-focused social networks.
  - Collaboration with technology websites and blogs.
  - Participation in blockchain-related technology conferences and events and live video.

- Livepeer Node Operators: Node operators who want to learn how to set up and manage nodes on the Livepeer network can be a key audience. They can be reached through:
  - Announcements and collaborations in Livepeer node forums and communities.
  - Participation in social networking groups where node operators share their experiences and knowledge.

- Publication of specific educational resources for node operators on blockchain and cryptocurrency-related websites and blogs.

- Live streaming entrepreneurs and startups: Companies and startups looking to integrate video transcoding services into their live streaming applications can be an important audience.

- People interested in learning about Livepeer and blockchain, in general, can be targeted students. They can be reached through:
  - Outreach programs at universities and education centers.
  - Creation of accessible online educational content, such as blogs and introductory videos.
  - Participation in education and technology events to attract a wider audience.

To reach these target students, it is important to use a combination of digital marketing strategies, collaborations with like-minded communities, and the creation of high-quality educational content. In addition, promotion through social media, online advertising, and participation in technology events can be effective tools to attract the right participants to Colledge training program in partnership with Livepeer. Also work hand in hand with our community partners such as GetOnBoard, GeekGirls LATAM, Angel Hack, Technolatinas, and Tribu LATAM.

### How did you learn about the Livepeer Grants Program?

Through a Grants research

### What's your wallet address?

0x98aa3e7F9dc7c456F77F7dF9e707bEa80B955108

### Do you consent to using "Powered by Livepeer" watermark on your application?

- [X] Yes
- [ ] No

**Comment by hansy** [comment]
Thanks for applying @cristpereirag. We'll get back to you with a decision within 2-4 weeks!

**Comment by cristpereirag** [comment]
Awesome! Thanks you!

**Comment by hansy** [comment]
Hi @cristpereirag! Thank you again for applying; unfortunately our team has decided not to fund this project at this time. Feel free to apply again in the future with additional updates and progress.

**Comment by cristpereirag** [comment]
Hi Hans, thanks for your reply. It is possible to have more information
about the decision? It is because the proposal is not clear? or something
that could be useful for use to try again?

Thanks in advance.

Best,
Cristobal

**Comment by hansy** [comment]
Hi @cristpereirag; that's a fair question. Your proposal was clear and concise, so no issues there. Our team's focus for the short term is funding more demand-driven applications (that contribute more activity to the Livepeer Network) vs educational initiatives, like your project. While there is tremendous value in educating new audiences about Livepeer, we're simply prioritizing other goals for now. I hope you understand.
