### ISSUE TITLE
[Open LN Grant]: WalletD

### ISSUE THREAD

**Issue by LivBoss** [livepeer/grants#184]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

Almost all blockchain projects, at their core, require wallet infrastructure. Even the most ambitious and innovative projects will need to interact with the blockchains they choose to operate on and, before they even come close to building their game-changing piece of technology, they will waste considerable time and resources on building their wallet infrastructure. Further to this, core infrastructure maintenance (hard, soft forks, and upgrades) require considerable resources. 

With our experience drawn from building and operating the most popular non-custodial Monero wallet, MyMonero, we know that building a wallet is difficult and that even one mistake can cause an entire project to fall apart. We have come to realize that almost the entire industry is wasting time and money on building something that should be easy and we’re all missing out on the true innovation that most developers and entrepreneurs intend to bring to their projects and the world. 

To solve this, we’re building a massive, open-source SDK which will include ready-to-use modules for noncustodial cryptocurrency wallets on as many different blockchains as possible. This will allow new and existing developers to instantly pull together a multicurrency wallet that supports whatever blockchains they want. In addition, the SDK will include modules with ready-made integrations with other services such as credit card on-ramps, in-app swaps, or wallet reporting tools.

At this stage, we have built out a brilliant- albeit small- team to develop and maintain our first few modules which are already live and available to the public. The aim is to build up our internal and community teams as quickly as possible to ensure that the project can keep growing and that developers have the ability to build out the tools of their dreams.

### Link to public GitHub repo (if applicable)

https://github.com/walletd/walletd

### Link to demo website (if applicable)

https://developer.walletd.org/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Generally, the development of a Livepeer module in the WalletD SDK will ensure that a reliable, secure Livepeer wallet (which supports both delegators and orchestrators) is available for any developer to include in their project or tool. Though this might sound underwhelming, the consequences are anything but underwhelming.

Firstly, what this wallet module will do is allow developers looking to build in the Livepeer ecosystem a foundation to build upon. Almost every blockchain project needs a wallet and WalletD will provide a fully-functional wallet module which can become the base upon which any future LPT tool could be built. However, this is just the tip of the iceberg.

The second and most important consequence of this module is that any developers building any blockchain project or tools can incorporate Livepeer into their project without the need for any additional resource spend. Livepeer as well as any Livepeer tools and functionality can quickly be incorporated into any multi-chain environment and become a part of the interconnected multi-ecosystem blockchain industry. This means that there will be increased exposure to Livepeer, increased use and trading of these tokens, and the potential for a wider range of tools becoming available to the Livepeer ecosystem.

### Please describe in details what your final deliverable for this project will be.

Milestone 1: 
Integration of WalletD modules into the Livepeer network and achieving feature parity with existing wallets.
Estimated Timeline: One month

Milestone 2:
Smart Contract Support. This would include, but is not limited to the development of the functionality within WalletD to enable the deployment of smart contracts which interact directly with Livepeer.
Estimated Timeline: One month

### Please break up your development work into a clear set of milestones

Milestone 1: 
Integration of WalletD modules into the Livepeer network and achieving feature parity with existing wallets.
Estimated Timeline: One month

Milestone 2:
Smart Contract Support. This would include, but is not limited to the development of the functionality within WalletD to enable the deployment of smart contracts which interact directly with Livepeer.
Estimated Timeline: One month

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Total requested funding across both milestones is $50,000.

In order to achieve these milestones, our project would require our full core development team.

Below is a breakdown of our monthly team costs, and the requested grant funding would cover a portion of these costs for one month:

Head of Engineering - Cost: $15,000
Senior Engineer 1 - Cost: $12,000
Senior Engineer 2 - Cost: $12,000
Senior Engineer 3 - Cost: $12,000
CEO / Founder/Ops: $20,000
Finance: $10,000

### Specify your team's long-term plans to maintain this software and upgrade it over time

Our long-term plans are to support as many blockchains as possible. We will leverage a comprehensive and efficient token-based incentive scheme to ensure committed and experienced community contributors to build and maintain these libraries. 

We will be creating an ecosystem based in the WalletD Token which can be earned by participating in the contribution to the open source SDK (which we call the Build2Earn program) as well as by utilizing the SDK in your own project infrastructure and sharing certain metrics about that product’s use (which we call the Grow2Earn program). The tokens themselves will also entitle the holders to a share of the entire project’s profit as well as allowing holders participation in the governance of the project.

See our Tokenomics Litepaper here: https://docsend.com/view/q6srtveubs6tuez3

We also aim to continuously expand our feature set, so as to ensure that we are a leading wallet infrastructure tool in every chain we support. An extremely important part of our long-term plans involves the maintenance of the security within our project. We will regularly conduct security audits and updates to ensure that the system is secure.

Long-term, we also intend to grow and expand our team, which will require investing in training and development in multiple blockchain environments. This will allow our engineers to experiment with new technologies that can improve our project and any project which is built using our SDK. Our long-term plans are flexible and adaptable. As blockchain technology is constantly changing, and so our team and our project goals constantly adjust accordingly.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Our competitive advantage sits in the experience of our team which consists of members of the Core Monero Team & Ex-Lead Maintainer of Monero; the development team behind the largest non-custodial Monero wallet, MyMonero; and legal and finance teams with over 5 years of experience in the cryptocurrency field with specific emphasis on wallet development and maintenance and open source project management. 

Riccardo Spagni - 
Our key team member, Riccardo Spagni has been involved in the cryptocurrency world since the early stages as he has been a member of the Monero Core Team since Monero’s inception. He acted as its first Lead Maintainer and was one of its core contributors for many years. Since then, he was the founder of cryptocurrency invoicing platform, GloBee; the founder and CEO of MyMonero; the Co-Founder of Tari (an upcoming smart contract protocol operating as a sidechain of Monero); Co-Founder of Yat; as well as a founder and CEO of a number of more traditional businesses.

Zaheer Seedat - 
Zaheer has previously worked in the financial sector with some reputable institutions, such as Deloitte South Africa, ABSA Bank, and Nedbank. 
He is currently the CFO for The Spagnis, which is an investment office focused mainly on the cryptocurrency and NFT industries. This has allowed him to gain extensive experience within the crypto space.
As a financial leader of 9-figure valuation crypto companies, he has become an asset as the CFO of Slaz.

Jonathan Purnell - 
Jonathan completed his Bachelor of Laws at the University of Cape Town and his Masters of Laws at New York University. He has 5 years experience working at the world renowned Norton Rose Fulbright as a tax attorney and being influential in the establishment of their cryptocurrency and blockchain practices. Since becoming the General Counsel for The Spagnis, as well as for Tari Labs, he has developed a deep understanding of the practical and regulatory laws within the crypto industry. He is currently the acting General Counsel for Slaz.

Devin Pearson - 
Devin operates at a senior level, with 15 years of software development under his belt.
He started out as a PHP Developer, and worked as a Software Architect for GloBee, where he started to grow his knowledge in crypto technology and development. With a massive amount of experience in the space, he has been a force to be reckoned with as the Lead Maintainer of MyMonero. He is putting his extensive knowledge of crypto tech to work as the Head of Engineering for Slaz.

Karl Buys - 
Karl has a strong 18 years of software development experience, which has given him extensive experience and a deep understanding of the dev environment. He operates at a senior level within the crypto dev space, and he put this extensive knowledge to work when he joined The Spagnis team as Development Lead. He then became a Core Developer at MyMonero, and has since become a strong asset to the Slaz team as a Senior Software Development Engineer.

Elaine Botha - 
Elaine has gained massive web and design experience over the past 14 years. She has worked on many international projects while leading the UI/UX team at the BMW Group South Africa. This experience has given her a deep understanding of technology and web design, which made her a brilliant addition to the Slaz team full-time as a UX/UI Developer.

Patrizio Spitalieri - 
Patrizio completed his Bachelors Degree in Business Administration and Management at Regent Business School. He built a high skill-set while working for GloBee as the head of Business Development and Operations. This gave him the edge when it came to understanding the inner workings of crypto in the business space. He then moved on to become the Head of Operations, Crypto Payments and Digital Asset Interoperability at MyMonero. The leadership and business development skills that he possesses are an asset to the Slaz team, where he now holds the role of Head of Operations and Growth.

### How did you learn about the Livepeer Grants Program?

Online research

### Was this project started at a hackathon or another web3 event? Which one?

No

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

Video Pitch: https://youtu.be/IQjXump9m84

Pitch Deck: https://docsend.com/view/pmmpxhgn8hr6s5kn

Please view our wallet CLI Demo hosted by our head of engineering here: https://www.loom.com/share/44c469525d434152b250d292078c350a?sid=62df1ba3-4b21-44c8-bdf4-9141f1a10be4

**Comment by hansy** [comment]
Thanks for applying @LivBoss! Our grants typically don't exceed $15k, so unfortunately we won't be able to fund this, unless you'd like pare down the milestones and amount to accommodate. If so, we're happy to review your updated application.
