### ISSUE TITLE
[Microgrant]: Implement Livepeer on RADAR Launch

### ISSUE THREAD

**Issue by RadarDAO** [livepeer/grants#187]
### What is your project, and what problem does it solve?

The only way to predict the future is to make it. However understanding, and building the future is currently held by those in power, with insight, resources and opportunities gatekept from builders and early adopters. Everyday, everybody already invests in the future. Who they follow, how they spend their time, what products they build, what products they use. 

But currently the platforms builders have to share their work on and get rewarded fail us. Public Forum social media, Transitory Hackathons, Mercenary grants don't truly align brands, builders and believers together.

In addition to this currently $7,567,137,950 has already been spent through kickstarter by believers and early adopters supporting builders, but those early adopters build no reputation for supporting them. They’ve no way to show they were early to a crowdfunding campaign, no way to show they were the first to support a product that then went on to make millions, and….they’ve also got no incentive to share that product with others.

RADAR Launch designed to connect builders and adopters to the future, and incentivise and reward them to make it a reality.

### Link to public GitHub repo (if applicable)

https://github.com/RadarDAO-xyz/radar-launch-frontend

### Link to demo website (if applicable)

https://radarlaunch.app/

### How is Livepeer used for this project?

1. Currently all the videos on the platforms, which allow builders to share their demos, visions and projects are pulled in via Youtube and Vimeo - leading to messy UX and public sharing settings causing errors. We want to move all videos onchain using livepeer so that builders have immutable evidence of building the future.
2. Currently builders can share an image to be an NFT, however we want to use Livepeer to make every video on the platform the NFT itself, creating a piece of onchain media

### How will you improve your project with this grant? What steps will you take to meet this objective?

Moving this media onchain for builders will vastly improve the UX and experience, as well as allowing it to become something others can integrate into platforms like interface.app and be read onchain.

We're going to:
1. Update create project form to use livepeer videos
2. Use livepeer videos as project thumbnails
3. Make all videos, video NFTs
4. Manually migrate current youtube / vimeo Videos on the platform to livepeer videos 

### Was this project started at a hackathon or another web3 event? Which one?

No, we've been building RADAR for the last 2 years, and have grown a community of 400+ professional forecasters, hobbiest, innovation specialists, degens and builders. We've run 2 x 10 week research sprints, created a collaborative white paper, run 2 hackathon events and worked with a number of web2 and web3 partners.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Fancy:

Fancy is a brand Strategist, Futurists and community builder. They have been full time in web3 for 3 years, they co-founded of Protein Community & RADAR, both decentralised communities at the forefront of web3. Protein is reimagining social impact through the lens of good growth. RADAR is full stack futures community. Fancy has run hundreds of workshops, multiple hackathons, and has deep roots in the web2 brand strategy and creative worlds. Fancy also advises brands entering the web3 landscape, a key stakeholder in SeedClub (SC02) and has written extensively on web3 models for ForeFront.

https://fancyy.xyz/

Marcus

Marcus is a fullstack web3 developer who attends regular hackathons (ETHTokyo, ETHParis, ETHMunich, ETHWarsaw, Solana Grizzlython) and has won prizes at ETHMunich, ETHWarsaw, and some local singapore hackathons. They're skilled in JavaScript, TypeScript, Java, C, Rust, PHP, Solidity and have a Bachelors of Computing, Computer Science at National University of Singapore, Ex-Bytedance.

Keels

With a nearly decade-long career grounded in creative strategy and qualitative consumer research, Today, she’s spearheading a Cultural Futurism practice within the strategy group at Dentsu: leveraging foresight to help brands understand — and future-proof — themselves in rapidly shifting context.

This is a unique team with a mix of strategic, cultural and development expertise to build a unique platform for the space.

### What is the project’s expected deliverable at the conclusion of the grant time period?

The Launch site is running with videos through livepeer and users are minting videos and collecting video NFTs, by the 6th of October

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

We want people to be 'signing' or 'believing' in projects, which adds a signature to the video NFT contract

### How will this deliverable benefit the Livepeer ecosystem?

More users uploading videos to livepeer

### Who is your target user group? How do you plan on obtaining them?

Our target user group are builders and early adopters.

1. Builders we're obtaining through partnering with hackathons to showcase builder projects
2. Early adopters and believers we're obtaining through 'believer rewards' where early adopters are rewarded by later adopters

We're also obtaining both user groups through allowing them to build onchain reputation on the platform

### How did you learn about the Livepeer Grants Program?

Spoke to LDF and then Alex 

### What's your wallet address?

0x149D46eC060e75AE188876AdB6b24024637003C7

### Do you consent to using "Powered by Livepeer" watermark on your application?

- [ ] Yes
- [X] No

**Comment by hansy** [comment]
Hey @RadarDAO. Here's the tx receipt for the upfront payment for the grant: https://arbiscan.io/tx/0xf9344df80df20c15c488bd24c63013ee523773b0d8267271533e262425bb79d7. Let me know if you have any questions!

**Comment by RadarDAO** [comment]
Thank you!

**Comment by hansy** [comment]
Here's the tx receipt for the grant completion: https://arbiscan.io/tx/0x22f77a5beb41088c84891cd83bc701b8a2eed2ed6b6de837768ed394b223e965. Let me know if you have any questions!

**Comment by RadarDAO** [comment]
Thank you! Appreciated, our next steps are to integrate believer splits into the platform to incentivise the user to collect. So will keep you updated!
