### ISSUE TITLE
[Open LN Grant]: RFP - Grants Node Operations

### ISSUE THREAD

**Issue by dob** [livepeer/grants#189]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

This a request for open proposals to take over the technical operations of the Livepeer Community Node technical node operations.

## Background

[The Livepeer Community Node](https://explorer.livepeer.org/accounts/0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc/orchestrating) is a special purpose node on the network which uses its LPT earnings to run [this grants program](https://github.com/livepeer/grants), with the LPT split between public goods funding and operations of the program itself. The node keeps a 50% reward cut, and thus relies on charitable/benevolent delegators, and its own accrued stake, to continue to earn rewards. The node currently does not transcode, and the operations of the node itself are a distraction from the work of the grants committee, which is focused more on evaluating grants applications and funding public goods and demand generating apps within the Livepeer Ecosystem. 

## Request for Proposal

The grants committee is open to proposals for taking over operations of the node itself, ideally introducing transcoding, so this is not just perceived as a "non-transcoding vampire node". Please include:

1. Operational proposal for how the node would be operated.
2. Security details for how the keys would be managed, and risk would be minimized over any potential loss of funds - now, and in the future should the agreement halt.
3. Compensation/incentive structure - ideally the transcoding fees earned through work would be sufficient.
4. How this plan would benefit the greater Livepeer ecosystem, rather than just yourself as an operator.

Thank you

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

See above

### Please describe in details what your final deliverable for this project will be.

A proposal to work with the grants committee on node operations.

### Please break up your development work into a clear set of milestones

The proposal is the only milestone.

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

While there may be compensation or incentive elements included in the actual proposals, this RFP does not require any payment, nor is there any payment for submitting a proposal.

### Specify your team's long-term plans to maintain this software and upgrade it over time

N/A

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

N/A

### How did you learn about the Livepeer Grants Program?

N/A

### Was this project started at a hackathon or another web3 event? Which one?

N/A

**Comment by dob** [comment]
For transparency, the grants committee has already received suggestions, ideas, and even a proposal on this front. Public accountability and transparency are positives, and part of the program's values, so all discussion or proposals are welcome. Though I do fully expect at least one quick proposal that matches this request to be provided soon.

**Comment by mikezupper** [comment]
Thank you Doug for preparing the RFP!

As a representative of the Video Miner Pool, I officially submit our proposal. The Video Miner Pool software was built specifically to address the needs of this RFP. 

[Video_Miner_Livepeer_Grant_Node_Proposal.pdf](https://github.com/livepeer/grants/files/12873837/Video_Miner_Livepeer_Grant_Node_Proposal.pdf)

**Comment by ChuckChain** [comment]
Just want to signal that we'll be throwing our hat in the ring. If it's not too late, we will submit a proposal here next week.

**Comment by dob** [comment]
Thank you for submitting these proposals. The grants team will review and be back shortly.

**Comment by ChuckChain** [comment]
Thank you @hansy and the rest of the grants committee for considering our proposal. And congratulations to @mikezupper and the Video Miner team - I'm sure they'll do a great job.

**Comment by mikezupper** [comment]
Thank you @hansy and the Livepeer grants team for selecting The Video Miner team. We have some work to do, but look forward to working with the community to make this initiative a success!
