### ISSUE TITLE
[Video Disruptors Grant]: Livepeer-IVA: Intelligent Video Analytics with Gstreamer and Livepeer

### ISSUE THREAD

**Issue by justmert** [livepeer/grants#190]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

Develop an Intelligent Video Analytics Application that leverages the power of GStreamer, NVIDIA DeepStream, and Livepeer. The primary problem we aim to address is the real-time analysis and processing of video streams tailored for distinct use-cases facilitated by specific DeepStream models: PeopleNet for human detection and tracking, FaceDetectIR for facial recognition even in low light conditions, and TrafficCamNet for vehicle detection and traffic analysis.

By utilizing Livepeer, our application seamlessly broadcasts live analytic feeds generated from real-time processing of video streams via GStreamer and NVIDIA DeepStream. Livepeer streamline real-time sharing of insights derived from specialized models but also leverage to store live video feeds, enabling on-demand analysis and review with recording feature.

### Link to public GitHub repo (if applicable)

https://github.com/justmert/livepeer-iva

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

**Benefits**

* Showcasing Livepeer’s capabilities in real-time video analytics domains. By leveraging specialized models like PeopleNet, FaceDetectIR, and TrafficCamNet for human detection, facial recognition, and traffic analysis etc., this project introduces various real-world use cases to the Livepeer ecosystem, thereby expanding the horizon of applications for Livepeer.

* Attracting more developers and industries to the Livepeer ecosystem. The project serves as a blueprint for integrating Livepeer with other powerful technologies like GStreamer for video streaming and NVIDIA DeepStream for video analytics. This technical integration showcase could inspire other developers and organizations to explore and create novel computer vision solutions using Livepeer.

* Enhancing Livepeer’s documentation and examples with real-world use cases.

* Bridging the existing gap in the Livepeer ecosystem regarding intelligent computer vision stream solutions. This initiative not only showcases Livepeer usage of delivering and recording intelligent video analytics but also provides a ready-to-use solution for Livepeer users with diverse needs in so many areas.

**Risks if not executed correctly**
Resource Drain: Poor GPU resource and memory management could lead to stream delays/recording failures.

**Execution Difficulties**
Integration Challenges: The integration of GStreamer, NVIDIA DeepStream, and Livepeer is technically complex and may present unforeseen challenges that could delay the project timeline.

### Please describe in details what your final deliverable for this project will be.

**Specification**

**Video Analytics**
Utilize PeopleNet, FaceDetectIR, and TrafficCamNet models for human detection, facial recognition, and traffic analysis.
Real-time analytics with capabilities including object detection, and object tracking.

**Video Streaming**
Integration with GStreamer to handle video streaming tasks. Seamless streaming of video analytics output to Livepeer, allowing users to view the analytics in real-time. Input source can be RTSP, or USB camera.

**Livepeer Integration**
Broadcast live analytic feeds on Livepeer’s decentralized video streaming platform.
Enable recording and on-demand retrieval of video streams through Livepeer.

**User Interface**
A user-friendly interface for users to interact with the application, view live streams, and access recorded video data.

**Documentation**
Comprehensive documentation detailing the setup, configuration, usage, of the application.

---

**Deliverables**

1. **Intelligent Video Analytics backend:** A fully-functional Intelligent Video Analytics backend integrated with Livepeer, GStreamer, and NVIDIA DeepStream for real-time video analytics, streaming, and recording. The application will be written in Python, and will be executed on Docker container that contains all the necessary dependencies.
    * The livestream will be created using Livepeer API.
    * The video analytics will be performed using NVIDIA DeepStream with specialized models.
    * The video streaming will be handled by GStreamer.
    * Processed output will be RMTP stream that will be broadcasted on Livepeer.
    * The application will be able to record the livestream using Livepeer API.
    * An API will be developed with FastAPI to handle the communication between the user interface.
    * Support for multiple input sources (RTSP, USB camera) will be provided.
    
2. **User Interface:** An intuitive user interface for interacting with the application will be developed using NextJS and Typescript.
    * Processed (model inferenced) livestream will be displayed on the user interface. The stream has bounding boxes around the detected objects (will be differ based on models).
    * Users can record the livestream and retrieve the recorded video to watch on-demand.
    * Adding new input sources (RTSP, USB camera) from the user interface.

3. **Dockerfile:** A docker-compose file will be provided for easy setup and configuration of the application
    * It will contain all necessary dependencies and configurations for the application to run on a machine with GPU support.

4. **Documentation:** A comprehensive documentation will be provided for the application.

---

**Scheme**

![livepeer-iva](https://github.com/livepeer/grants/assets/37740842/02b4800c-a23b-4836-8568-571ebe559390)

### Please break up your development work into a clear set of milestones

| Count  | Milestone | Deliverable  |  FTE - Role  | Amount  | Achieve Est. Time |
|---|---|---|---|---|---|
|  1 |  **Intelligent Video Analytics backend**  | Written in Python and integrated with Livepeer, GStreamer, and NVIDIA DeepStream for real-time video analytics, streaming, and recording. Deliverables for this milestone is specified in deliverable 1.   | 1 FTE - Developer  |  8,500 USD | 27.11.2023  |
|  2 |  **User Interface** | User interface for interacting with the application written in NextJS and Typescript. Deliverables for this milestone is specified in deliverables 2.   | 1 FTE - Developer |  4,500 USD |  25.12.2023 |
|  3 |  **Dockerfile and Documentation** | A dockerfile that contains all necessary dependencies and configurations for the application and comprehensive documentation for usage and setup of the application. Deliverables for this milestone is specified in deliverables 3,4   | 1 FTE - Developer |  2,000 USD |  12.01.2024 |

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

* Total Budget Requested: 15,000 USD

The funds will compansate for the time spent on the project. The fund will also be used to cover long term maintenance and upgrades of the application.

### Specify your team's long-term plans to maintain this software and upgrade it over time

The project will be open-source and maintained by the me. I will responsible for fixing bugs, adding new features, and upgrading the application over time. Any contributions from the community will be welcomed and reviewed. Also I am going to continually integrate new models to improve the capabilities of the application. Besides, the speed is of the essence in real-time video analytics so optimizing the processing pipeline to reduce latency is necessary to ensure the real-time delivery of analytics.

I have thoughs to integrate the application with [bacalhau](https://github.com/bacalhau-project/bacalhau) (Distributed Computation Framework by Filecoin) to leverage the power of Filecoin for distributed computation. This will allow non-GPU users to utilize the application for video analytics to replace local GPU resources with Filecoin's distributed computation power to scale to more users and more video streams. Bacalhau still in heavy development, and will try when it is ready.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

As an experienced Web3 developer, I have become a grantee for Web3 Foundation, AAVE, Lens and Filecoin and other ecosystems by developing innovative projects. As a certified NVIDIA instructor, AAVE Turkey Community Co-Manager and ambassador for organizations such as Microsoft and The Graph protocol. Currently, I'm focused on developing open-source and user-friendly applications that bring value in blockchain area.

I have worked as Intelligent Video Analytics Team Leader in a NVIDIA distributer company that develops video analytics solutions for 2 years. I have experience in developing video analytics solutions using NVIDIA DeepStream, GStreamer, and Python. Created a AI computer vision engine that powers a [video analytics platform](https://cordatus.ai/home/) that is used by many companies in Turkey. 

Also created a small project called [IPIVA](https://github.com/justmert/IPIVA) that provides decentralized AI video analytics with syncing AI model metadata across OrbitDB peer networks.

* Mail: kklumert@gmail.com
* Discord: MertK#2634
* Linkedin: https://www.linkedin.com/in/mertkoklu/
* Github: https://github.com/justmert
* Location: Ankara, Turkey

### Who is your target user group? How do you plan on getting your users to use this?

The target user group can be organizations, Livepeer community, and users who need video analytics applications for traffic management, monitoring solutions, as well as developers and companies keen on integrating advanced video analytics into their systems. 

To engage and grow our user base, we plan to approach communities through platforms like Discord and Livepeer forums. Additionally, providing comprehensive documentation, and guide to help users on leveraging the application effectively. Gathering valuable feedback via Discord, forums, or Github issues to improve user experience, making the application more user-friendly.

### How did you learn about the Livepeer Grants Program?

Livepeer Github

### Was this project started at a hackathon or another web3 event? Which one?

No, it isn't.

### Do you consent to using "Powered by Livepeer" watermark on your application?

- [X] Yes
- [ ] No

**Comment by hansy** [comment]
Thanks for applying @justmert! We'll get back to you with a decision within 2-4 weeks!

**Comment by iameli** [comment]
My quick take: I love this feature but the Livepeer integration is pretty shallow. I think I'm 100% open to something of this scope if we worked out how this could be come a feature _of_ the Livepeer network, rather than something with a relatively shallow Studio integration. I'd be totally willing to meet and talk through how this could happen with the team though!

**Comment by dob** [comment]
I echo @iameli's comments a bit: if I'm understanding correctly, the Livepeer Studio API is being used here to stream + record a "stream of realtime analytics". Is that like an analytics dashboard view? Or an overlay of stats onto the original stream? Either way, it is a light integration/enhancement to Livepeer.

This could be ok if the output was critical for an actual go-to-market behind a self motivated business that was targeting, as you mention, the traffic monitoring industry? But if it's purely a demonstration of an open source technology workflow, then I think the more valuable thing would be to add these capabilities into the Livepeer stack itself. For example adding the Intelligent Video Analytics capability into Catalyst.
